podman-desktop/extension-bootc

src/extension.ts
fixes and cleans up vfkit launch
* moves the button to where the containers is (for now)
* adds labels to the build image
* does some checks before launching the VM
=> fixes and cleans up vfkit launch

package.json
=> add command

src/extension.ts
Logs an event whenever users with telemetry enabled do a build or try to launch vfkit, with basic anonymous details. We need to see what data this produces and it will clearly need to change as we evolve the extension, but gives us a basic view for now.
Fixes #23.
=> feat: basic telemetry

src/extension.ts, src/launch-vfkit.ts
Move vfkit launching to its own file. No changes to implementation.
N/A
Part of #55.
Just moving existing function, in part so tests can be targeted and clearly separated too.
=> chore: refactor vfkit

.github/workflows/pr-check.yaml, src/extension.spec.ts
Initial PR check with linting, formatting, and tests.
May need a couple attempts, but I think this has all the basics.
N/A
Part of #36.
Hopefully, it's the first PR that tests itself. ;-)
=> feat: PR check and initial test

README.md
Update README.md add videos and pictures
Updates the README.md to add pictures and videos and a more in-depth
explanation for the extension.
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/57
=> Update README.md add videos and pictures

.eslintrc.json, package.json, yarn.lock
Title says it all: saw another extension do this, figure we should too.
N/A
N/A
PR check.
=> chore: pick up missing linting from podman desktop

src/build-disk-image.ts, src/container-utils.spec.ts, src/container-utils.ts
feat: clean containers and volumes up after a build
* Removes the container after a success or unsuccessful build
* Removes any volumes created as a result of running the build
Other fixes:
* Moves the await show error message to outside of the try / catch as
using 'await' on it was blocking the 'finally' statement regarding
cleaning up
* Moves the "create container options" outside of the try / catch as it
is not an async statement / it is just a generator
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/e2c6cdf1-cf29-412a-8e90-aae29a1a55e8
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/48
1. Start a build
2. Stop the container mid-build
3. See the error output from building it
4. See that the container has been removed / any volumes …
=> feat: clean containers and volumes up after a build

package.json, yarn.lock
Step up to a new PD build that has the latest API (and will do so again once 1.7 is released).
N/A
N/A
PR checks.
=> chore: podman desktop API

Containerfile
Update the containerfile to require PD 1.7.
N/A
N/A, just moving up to release.
Install from ghcr.
=> chore: update containerfile to PD 1.7

src/constants.ts
New image builder from yesterday is working well in my tests. As far as I can tell it doesn't add any of the features we're waiting for, but presumably has fixes.
N/A
N/A
Do a variety of builds.
=> chore: update image builder

src/build-disk-image.ts
We need to include the image tag to work with anything other than latest.
N/A
Fixes #90.
Tag the image before pushing and try to build it.
=> Support tagged images

src/container-utils.ts
We should really be using console.error() for errors, .warn() for warnings.
N/A
N/A
N/A
=> chore: console error

src/container-utils.spec.ts
Core of copyright missing compared to other files.
N/A
N/A
N/A
=> chore: fix copyright

README.md, docs/containerfile_guide.md, docs/vm_guide.md, examples/bootc-helloworld-python-systemd/Containerfile, examples/bootc-helloworld-python-systemd/helloworld.py, examples/bootc-helloworld-python-systemd/helloworld.service, examples/bootc-helloworld-quadlet-container/Containerfile, examples/bootc-helloworld-quadlet-container/helloworld.container
Adds A LOT more information regarding how to use bootc / containerfile /
quadlets / etc.
N/A, preview the markdown.
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/66
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/33
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/26
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/25
N/A, preview the markdown.
=> docs: Documentation rewrite

README.md
Removes (now incorrect) text about commits, and lists the steps so that you don't need to watch the video (or if it's not there).
N/A
N/A
N/A
=> chore: update install instructions

README.md
Add topics to the readme so that you can see what it includes and jump to a section. Renamed a few section titles to make them shorter or more consistent.
N/A
Fixes #119.
Test each link.
=> chore: add topic list to readme

.github/workflows/pr-check.yaml
Just updates to macos-14 runner.
N/A
Fixes #134.
PR check.
=> chore: update to macos-14 runner

README.md
Add support for Windows since #94 is closed
=> docs: add windows support in README.md

docs/vm_guide.md
As it has streamlining this as its explicit goal in life.
=> vm_guide: Link to podman-bootc CLI

packages/backend/src/build-disk-image.ts
Fixing two minor issues related to the end of the build task:
- The bug in PD that required us to report an increment of -1 to trigger task completion appears to have been fixed a while ago. Better to report 100%.
- Currently, the dialog to tell you that the job is successful blocks the task from finishing until you say OK. It should be async.
N/A
Fixes #232.
=> chore: fix end status

packages/backend/src/build-disk-image.ts
Fixes async call that stopped logging.
<!-- If this PR is changing UI, please include 
N/A
Fixes #209.
Build, confirm log file is correct now.
=> fix: async call to log

.github/workflows/pr-check.yaml, README.md, package.json
docs: update contributing and `yarn test`
* Updates documentation on how to do testing / formatting / typechecking
/ etc.
* Switches from `yarn test:unit` to `yarn test`
N/A
References: https://github.com/containers/podman-desktop-extension-bootc/issues/247
`yarn test`
=> docs: update contributing and `yarn test`

.github/workflows/release.yaml
A little crude, but updates all three package versions to the same version.
N/A
N/A
Next release.
=> chore: update all packages

README.md
docs: installation steps
Updates the installation steps so it's a list rather than having to read
through the paragraph / trying to find the copy and paste image link.
N/A
N/A
N/A
=> docs: installation steps

README.md
docs: minor update to ram requirement for podman machine
Should document that at least 6GB is required
N/A
N/A
N/A
=> docs: minor update to ram requirement for podman machine

packages/frontend/package.json, tests/playwright/package.json, yarn.lock
=> chore: update to Podman Desktop v1.9.0 API

packages/backend/src/build-disk-image.ts, packages/backend/tsconfig.json, packages/shared/src/messages/MessageProxy.ts, packages/shared/src/models/bootc.ts
Following what AI Lab did, just upping our backend tsconfig settings.
N/A
Part of #247.
Just adds additional checks to PR build.
=> chore: strict tsconfig

packages/backend/src/build-disk-image.ts, packages/backend/src/extension.spec.ts, packages/backend/src/history.spec.ts, packages/backend/src/machine-utils.spec.ts, packages/frontend/src/lib/BootcEmptyScreen.spec.ts, packages/frontend/src/lib/NoBootcImagesEmptyScreen.spec.ts
We have a lot of no-explicit-any, but several of them appear to be copy pasta or things we fixed earlier. Just removing a bunch of them that appear unnecessary.
N/A
Part of #247.
Existing PR checks should catch any regression.
=> chore: reduce no-explicit-any

package.json, yarn.lock
Remove unnecessary/unused dependency.
N/A
N/A
PR checks are enough.
=> chore: remove simple-git

packages/backend/src/api-impl.ts, packages/frontend/src/Homepage.svelte
Be clear whenever we talk about images if it is a disk image or container image. This likely isn't all of them, just a couple I saw today.
N/A
N/A
Check homepage table tooltips and empty screen text.
=> chore: disk image naming

packages/backend/src/constants.ts
Latest build of the bootc-image-builder.
N/A
N/A
PR tests, build a few images.
=> chore: bib latest-1712917745

docs/vm_guide.md
docs: add more arm64 / amd64 instructions
Adds more arm64 / amd64 instructions in order to test image building.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/354
Test commands
=> docs: add more arm64 / amd64 instructions

packages/backend/src/constants.ts
Update to latest bib image.
N/A
N/A
Build a few images of different types.
=> chore: bib latest-1713548482

README.md, packages/backend/package.json, yarn.lock
Update the API and dependency on Podman Desktop 1.10.0 or higher.
N/A
Fixes #352.
Automated tests, do a build.
=> chore: update to PD 1.10

tests/playwright/src/bootc-extension.spec.ts
Updates e2e tests for bootc
`yarn test:e2e`
=> chore(test): update to e2e tests

docs/vm_guide.md
docs: add some simple instructions on post-building usage
Adds some simple explanations on how to use each format.
We should not go into too much detail as there are **many** solutions to
how to run raw, qcow2, etc, and that generic links should be sufficient.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/82
N/A
=> docs: add some simple instructions on post-building usage

README.md
docs: remove experimental testing section
Removes a very not-safe / recommended section that was used for
developmental purposes of bootc.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/357
N/A
=> docs: remove experimental testing section

packages/frontend/src/Build.svelte
as suggested there https://github.com/containers/podman-desktop-extension-bootc/issues/317#issuecomment-2079661678, apply minimal style to make the checkbox with a tick
fixes https://github.com/containers/podman-desktop-extension-bootc/issues/317
click on checkboxes in Build section
=> chore: apply minimal checkbox styling (add check in checkboxes)

README.md
docs: update readme with simplified information and added gifs
* Updates the readme steps to be a lot more simplified (we no longer
need to push.. the logs are shown in the folder / can be found easily,
etc.)
* Added gifs
See README.md
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/382
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/338
View the README.md, make sure that the gifs are there. Make sure that
the steps are accurate.
=> docs: update readme with simplified information and added gifs

README.md
docs: remove experimental disclaimer
IMO we are stable enough to remove experimental
N/A
N/A
N/A
=> docs: remove experimental disclaimer

packages/backend/src/build-disk-image.spec.ts, packages/backend/src/build-disk-image.ts
Just switches createBuilderImageOptions() to use BootcBuildInfo instead of adding individual parameters each time.
N/A
N/A
Tests updated.
=> chore: simplify createBuilderImageOptions parameters

README.md
docs: update installation via catalog and nightly version
Adds instructions / gif on how to install via the catalog as well as how
to use the nightly version.
N/A
N/A
N/A
=> docs: update installation via catalog and nightly version

README.md
docs: update linux command to include memory
Adding --memory 6144 will help linux users set there ram to the required
minimum amount for the extension to work well.
N/A
N/A
N/A
=> docs: update linux command to include memory

tests/playwright/src/bootc-extension.spec.ts
Removes an unused param from a test method.
https://github.com/containers/podman-desktop-extension-bootc/issues/514
=> chore(tests): remove unused param

packages/backend/src/extension.spec.ts, packages/backend/src/extension.ts
Remove code to support old podman desktop nightly version and update tests.
N/A
Fixes #546.
Automated tests updated.
=> chore: new podman desktop nightly version

packages/frontend/src/Homepage.svelte
Allows us to move to PD UI package 1.11.0.
N/A
N/A
Just build checks.
=> chore: remove column type

packages/backend/src/build-disk-image.spec.ts, packages/backend/src/build-disk-image.ts
chore: add podman command equivilant output in logs
For debugging, it is nice to provide upstream (bib team) the podman
equivilant command.
This adds it to the log so it helps in terms of debugging.
```
Folder: /Users/cdrage/bootc/qemutest5
----------
{
"name": "test123-bootc-image-builder-2",
"Image": "quay.io/centos-bootc/bootc-image-builder:latest-1714633180",
"Tty": true,
"HostConfig": {
"Privileged": true,
"SecurityOpt": [
"label=type:unconfined_t"
],
"Binds": [
"/Users/cdrage/bootc/qemutest5:/output/",
"/var/lib/containers/storage:/var/lib/containers/storage"
]
},
"Labels": {
"bootc.image.builder": "true"
},
"Cmd": [
"localhost/test123:latest",
"--output",
"/output/",
"--local",
"--type",
"raw",
"--target-arch",
"amd64"
]
}
----------
podman run \
--name …
```
=> chore: add podman command equivilant output in logs

.github/workflows/build-next.yaml, .github/workflows/pr-check.yaml, .github/workflows/release.yaml, package.json
use Node.js v20 as the electron's version
=> chore: fix node requirements

packages/frontend/package.json, yarn.lock
allow to ensure to use latest changes with svelte5 being also used in the library
=> chore: update to the librry using svelte v5

packages/backend/src/constants.ts
Update to latest-1720185748 build.
N/A
Fixes #580.
Build some disk images!
=> chore: new bootc image builder

tests/playwright/src/model/bootc-page.ts
Attempt to fix bootc e2e tests failing on windows
https://github.com/containers/podman-desktop-extension-bootc/issues/629
=> chore(test): add some debug logs

.github/workflows/bootc-e2e-nightly-windows.yaml
Updates the nightly yaml to use the latest image for provisioning.
https://github.com/containers/podman-desktop-extension-bootc/issues/697
=> chore(test): update image used for provisioning

packages/frontend/package.json, packages/frontend/src/Build.svelte, yarn.lock
Updates to latest UI library.
See #561.
Fixes #561.
Fixes #622 (but already fixed by changes in Podman Desktop).
Look at status icon during different states of a build.
=> chore: update to latest UI library

packages/frontend/src/Build.svelte
Just need to move up to Svelte 5 syntax for event handling, due to moving up to current UI package.
N/A
Fixes #720.
Just test breadcrumbs.
=> chore: adopt svelte 5 hander to fix breadcrumb

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml
…ge.json
Manually adjust the `@podman-desktop/tests-playwright@next` version in package.json file.
#712
=> chore: change the way to include @podman-desktop/tests-playwright

CODEOWNERS
Align CODEOWNERS with other Podman Desktop repositories
N/A
N/A
N/A
=> chore: align CODEOWNERS

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, package.json, tests/playwright/vitest.config.js
Switches to building PD using pnpm for e2e test purposes.
https://github.com/containers/podman-desktop-extension-bootc/issues/778
=> Switch pd to pnpm

packages/backend/src/api-impl.ts, packages/backend/src/build-disk-image.ts, packages/backend/src/container-utils.spec.ts, packages/backend/src/container-utils.ts, packages/backend/src/machine-utils.spec.ts, packages/backend/src/machine-utils.ts
Fixes #722
Properly handle libkrun machines
N/A
#722
1. Create a libkrun machine
2. Initiate a bootc build
=> fix: handle libkrun machines

.gitignore, tests/playwright/src/bootc-extension.spec.ts
Fixes the condition for skipping the extension installation test in PR check
=> chore(tests): fix ext. installation skip condition

tests/playwright/src/bootc-extension.spec.ts
Updates the e2e tests for the latest changes in the test framework.
https://github.com/containers/podman-desktop-extension-bootc/issues/791
=> chore(test): update e2e tests to work with framework

packages/backend/src/build-disk-image.spec.ts, packages/backend/src/constants.ts
chore: update bib to incorporate new changes
Updates bib to incorporate changes for adding btrfs
Tested on Windows and macOS building images.
N/A
N/A
Build an image and see if it passes for raw, iso, qcow2, etc.
=> chore: update bib to incorporate new changes

packages/backend/src/build-disk-image.spec.ts, packages/backend/src/build-disk-image.ts, packages/backend/src/extension.spec.ts, packages/backend/src/history.ts, packages/backend/src/history/historyNotifier.spec.ts, packages/frontend/src/Build.spec.ts, packages/frontend/src/Homepage.spec.ts, packages/frontend/src/lib/BootcActions.spec.ts, packages/frontend/src/lib/BootcColumnActions.spec.ts, packages/frontend/src/lib/BootcFolderColumn.spec.ts, packages/frontend/src/lib/BootcImageColumn.spec.ts
I've already hit a merge conflict with #769, so this is an attempt to get a few of the code changes that will be required in early:
- Don't use /tmp in test folder names (we're not writing to disk, so name is meaningless anyway).
- Use String.startsWith() over String.charAt(0).
- Don't use indexed for loop.
N/A
First part of sonar upgrade in #769.
Regular PR check.
=> chore: code cleanup

packages/frontend/src/Build.spec.ts
As part of sonar updates in #769 you can no longer use the test pattern `expect(x.classList.contains('y'))` because it always passes - and indeed several of our build tests have been silently failing for a while (passing when they should have failed).
The tests should be checking for attributes like checked/disabled instead of styling classes; they were also broken due to moving to the Checkbox component, light mode, and usability improvements in the UI.
I'm putting this up for review separately since while sonar found the underlying failure this change isn't dependent on it.
N/A
Required by / part of  #769.
PR check; confirm test logic.
=> chore: fix invalid build tests

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml
Archive artifacts now should preserve all test artifacts on CI.
#820
=> fix(ci): use correct glob pattern for test artifacts

.github/workflows/release.yaml
The release workflow was missing a step to install pnpm.
N/A
Fixes #850.
We'll try releasing again.
=> fix: release workflow didn't install pnpm

packages/frontend/package.json, pnpm-lock.yaml
Update vite-plugin-svelte to v4 to support svelte v5.
N/A
N/A
PR check.
=> chore: update vite-plugin-svelte

.github/workflows/bootc-e2e-nightly-windows.yaml
PR updates URL to podman5.json after changes in podman extension directory structure
=> fix: update path to podman5.json after podman extension changes

package.json, packages/backend/package.json
Publisher needs to be fixed to match other extensions.
N/A
Fixes #905.
N/A
=> chore: update publisher

packages/frontend/src/Build.svelte
chore: typo for anaconda
Anacoda => Anaconda
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/916
N/A
=> chore: typo for anaconda

package.json, packages/backend/package.json
This reverts PR #906 / commit bd8d3dae244ea677c7fa10d3f6f66e4c4f523a51.
N/A
Fixes #922.
=> chore: revert "chore: update publisher"

.github/dependabot.yml
Avoid duplicate update for the same group
- https://github.com/podman-desktop/extension-bootc/pull/1033
- https://github.com/podman-desktop/extension-bootc/pull/1032
=> chore(deps): group commitlint updates

.github/workflows/e2e-main.yaml
It is an attempt to fix e2e-tests-main test execution, which is failing to install pnpm.
=> fix: e2e-tests-main workfow failure to install pnpm

RELEASE.md
docs: update release doc
Updates the release documentation
N/A
N/A
N/A
=> docs: update release doc

.github/workflows/e2e-main.yaml, pnpm-lock.yaml, tests/playwright/package.json
=> fix: e2e test errors

packages/frontend/src/Build.svelte
Just indents the sections and moves the image types to two columns. Literally only adding a couple divs, but poor diff may make it look like more.
Before:
After:
Fixes #1216.
Open Build page and each section.
=> chore: minor polish for build page

package.json, pnpm-lock.yaml
See issue for details - picking up older globals is causing lint failures so adding a direct dependency.
N/A
Fixes #1253.
PR checks.
=> chore: update globals package

packages/backend/src/extension.ts
Backport of #1274 to 1.6.
N/A
Part of #1275.
PR checks.
=> fix: create storage path (#1274)

packages/backend/src/machine-utils.spec.ts
cleanup entries and make sure to mock Podman Desktop API env and not the os library
I noticed that as it's failing with new vite* versions
https://github.com/podman-desktop/extension-bootc/pull/1287
https://github.com/podman-desktop/extension-bootc/pull/1287
unit tests should be 💚
=> chore: fix the unit tests

eslint.config.mjs, packages/frontend/src/Build.spec.ts, packages/frontend/src/Build.svelte, packages/frontend/src/lib/ExampleCard.svelte, packages/frontend/src/lib/ExamplesCard.svelte, packages/frontend/src/lib/Link.svelte, packages/frontend/src/lib/dashboard/Dashboard.svelte, packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.svelte, packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.spec.ts, packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte, packages/frontend/src/lib/navigation.ts, packages/frontend/src/stores/rpcReadable.spec.ts
Enable the remaining two linting rules for promises, even redoing some of the code I 'fixed' last week because there's a better change once you have more linting enabled.
N/A
Fixes #1245.
Code review; PR checks.
=> chore: enable promises linting

packages/backend/src/api-impl.ts, packages/frontend/src/api/client.ts, packages/frontend/src/stores/rpcReadable.spec.ts, packages/shared/src/BootcAPI.ts, packages/shared/src/messages/MessageProxy.spec.ts, packages/shared/src/messages/MessageProxy.ts, packages/shared/src/messages/NoTimeoutChannels.ts, packages/shared/src/messages/utils.ts
Multi-channel rpc, matching AI Lab. This doesn't give us a direct benefit by itself, but would allow us to start splitting the 29 functions in the current API up better / allow for growth, and alignment with AI Lab will make it easier to share future improvements/debugging.
N/A
Fixes #1265.
PR checks, make sure lists/examples still have data.
=> chore: multi-channel rpc

.github/dependabot.yml
Same change as Podman Desktop, just create groups to cut down on dependabot PRs.
N/A
N/A
Check next dependabot PRs.
=> chore: dependabot grouping

package.json, pnpm-lock.yaml
fixes https://github.com/advisories/GHSA-67mh-4wv8-2f99
=> chore: fix CVE on esbuild

.github/workflows/bootc-e2e-nightly-windows.yaml
Updates the windows cicd workflow
https://github.com/podman-desktop/extension-bootc/issues/1279
=> chore(test): update workflow file

.github/workflows/bootc-e2e-nightly-windows.yaml, .github/workflows/e2e-main.yaml
=> chore: fix trailing spaces

package.json, packages/backend/package.json, pnpm-lock.yaml
version is outdated (and the same for the svelte plugin)
https://github.com/podman-desktop/extension-bootc/pull/1415
pr checks should be 💚
=> chore: update eslint

package.json, packages/backend/package.json, pnpm-lock.yaml
=> chore(deps-dev): bump eslint-import-resolver-typescript

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, tests/playwright/src/bootc-extension.spec.ts
Changes the param in build-image function to be aligned with change in pd-core upstream npm package.
#1434
=> fix: update build image function call after change

package.json
Updates node and pnpm to match Podman Desktop. May unblock dependabot svelte PR.
N/A
Related to #1429..
Just PR checks.
=> chore: update node to match pd

README.md, packages/frontend/src/lib/dashboard/Dashboard.svelte
The bootc github org changed, need to fix the broken links.
N/A
Fixes #1452.
Click on bootc link on Dashboard or readme.
=> fix: broken links to bootc org

packages/frontend/src/lib/BootcSelkie.svelte, packages/frontend/src/lib/DiskImageIcon.svelte
Update the icon components to Svelte 5. The class and style properties were unused and I don't foresee any need for them, so I removed them instead of migrating.
N/A
Part of #1295.
PR checks, code review.
=> chore: update icon components to svelte 5

tests/playwright/resources/bootable-containerfile, tests/playwright/src/bootc-extension.spec.ts, tests/playwright/src/model/bootc-examples-page.ts
Fixing some flakyness issues that occur on slower environments/platforms.
https://github.com/podman-desktop/extension-bootc/issues/1501
=> chore(test): addressing some robustness issues in bootc tests

package.json
=> chore: update pnpm to v10

packages/frontend/src/stores/rpcReadable.ts
Uses nullish coalescing operator ??= instead of previous pattern.
N/A
Should help with dependabot eslint update #2195.
Just code review.
=> chore: use nullish coalescing operator

tests/playwright/src/bootc-extension.spec.ts, tests/playwright/src/model/bootc-page.ts
Tries to better handle test flakyness that comes from pulling big images on cloud environments.
=> chore(test): switching to smaller image to reduce test flakyness

pnpm-lock.yaml
Updates babel runtime to avoid CVE.
N/A
Fixes #1517.
PR review, checks.
=> chore: update babel/runtime to fix CVE

tests/playwright/src/bootc-extension.spec.ts, tests/playwright/src/model/bootc-dashboard-page.ts, tests/playwright/src/model/bootc-page.ts
Dashboard image e2e test
https://github.com/podman-desktop/extension-bootc/issues/1375
=> chore(test): dashboard image e2e test

packages/frontend/src/Build.svelte
chore: add example for ssh key
Adds to the build page what an SSH key input should look like
N/A, super minor, just check code :)
N/A, brought on a quick call.
Check build page
=> chore: add example for ssh key

.github/workflows/build-next.yaml, .github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, .github/workflows/release.yaml, packages/backend/package.json, pnpm-lock.yaml
chore: update dependencies and CI workflows for macadam
* Update .github workflows
* Update dependencies in package.json and pnpm-lock.yaml
N/A
Reference: https://github.com/podman-desktop/extension-bootc/issues/1521
Follow regular CI pipeline checks.
=> chore: update dependencies and CI workflows for macadam

packages/backend/src/macadam.spec.ts, packages/backend/src/macadam.ts
Moves VM creation into a task (withProgress) and adds telemetry with the image type, pass/fail, and error message.
https://github.com/user-attachments/assets/e0156069-a3b2-4b58-8c18-ba8520bdfede
Part of #1588.
Create an image and confirm task was created.
=> chore: add telemetry and task for creating vm

.github/dependabot.yml
try to specify data for the npm package registry
=> chore: try to use GH token

.github/dependabot.yml
=> chore: apply prettier on the dependabot file

.npmrc
specify which package registry to use for crc-org packages
dependabot updates
=> chore: add package to .npmrc file

.github/dependabot.yml, .github/workflows/build-next.yaml, .github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, .github/workflows/release.yaml, .npmrc, packages/backend/package.json, packages/frontend/package.json, pnpm-lock.yaml
It doesn't require anymore auth
>***note*** ensure to remove any custom .npmrc / specific auth for @crc-org package that you may still have locally
https://github.com/podman-desktop/extension-bootc/issues/1596
=> chore: switch to npmjs package of crc-org binary

packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts, packages/frontend/src/lib/disk-image/DiskImagesList.svelte
chore: do not show Create VM button for windows.
* Do not show button on windows, only linux and macOS
* Switches onMount to async, so added an unsubscriber for the filter
N/A, no longer should see the button on Windows.
Closes https://github.com/podman-desktop/extension-bootc/issues/1646
1. Go on Windows
2. Do not see button :)
=> 1.9.x: chore: do not show Create VM button for windows.

packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts, packages/frontend/src/lib/disk-image/DiskImagesList.svelte
chore: do not show Create VM button for windows.
* Do not show button on windows, only linux and macOS
* Switches onMount to async, so added an unsubscriber for the filter
N/A, no longer should see the button on Windows.
Closes https://github.com/podman-desktop/extension-bootc/issues/1646
1. Go on Windows
2. Do not see button :)
=> chore: do not show Create VM button for windows.

packages/backend/src/macadam.spec.ts, packages/backend/src/macadam.ts
See https://github.com/crc-org/macadam/issues/180 for background. Macadam is picking up the provider from .config/containers/containers.conf and fails on Mac when it uses libkrun.
This uses the same logic as the RHEL extension to explicitly set the provider option so that it doesn't get picked up from the file: https://github.com/redhat-developer/podman-desktop-rhel-ext/blob/main/src/extension.ts#L470
Does the correct thing for windows as well even though we don't support it yet. Added tests for all three platforms.
N/A
Fixes #1645.
Set the provider in .config/containers/containers.conf to "libkrun" and have VM creation fail on 1.9, but same works fine after this fix.
=> fix: set macadam provider to the correct value

packages/backend/src/macadam.spec.ts, packages/backend/src/macadam.ts
See https://github.com/crc-org/macadam/issues/180 for background. Macadam is picking up the provider from .config/containers/containers.conf and fails on Mac when it uses libkrun.
This uses the same logic as the RHEL extension to explicitly set the provider option so that it doesn't get picked up from the file: https://github.com/redhat-developer/podman-desktop-rhel-ext/blob/main/src/extension.ts#L470
Does the correct thing for windows as well even though we don't support it yet. Added tests for all three platforms.
N/A
Fixes #1645.
Set the provider in .config/containers/containers.conf to "libkrun" and have VM creation fail on 1.9, but same works fine after this fix.
=> 1.9.x: fix: set macadam provider to the correct value

packages/frontend/package.json, pnpm-lock.yaml
Switch to Svelte 4.33.13
N/A
N/A
Run unit tests
=> chore(deps-dev): update svelte to v4.33.13

tests/playwright/src/bootc-extension.spec.ts, tests/playwright/src/model/bootc-page.ts
Tries to fix broken bootc windows e2e tests
=> chore(test): fixing some flakyness

tests/playwright/src/bootc-extension.spec.ts, tests/playwright/src/model/bootc-page.ts
Workaround for e2e tests to run on azure cicd until https://github.com/podman-desktop/extension-bootc/issues/1701 is fixed.
https://github.com/podman-desktop/extension-bootc/issues/1701
=> chore(test): workaround to make e2e tests run on azure cicd

package.json, packages/backend/package.json, packages/frontend/package.json, pnpm-lock.yaml
Switch to vite 7.0.2
N/A
N/A
Check workflows
=> chore: switch to vite 7.0.2

tests/playwright/src/bootc-extension.spec.ts
Increases timeout for image pulling in bootc
=> chore(test): increasing timeout for cicd

packages/frontend/src/lib/examples/Examples.svelte
Migrate Map to SvelteMap in example to help update of linter to pass
This is to help update of package in PR #1809
=> chore: use SvelteMap in Example to make update of linter pass

tests/playwright/src/model/bootc-images-page.ts
Tries to fix broken e2e tests in cicd
=> chore(test): fixing broken locator

CONTRIBUTING.md
Update repository name in Contributing instructions to help collaboration.
=> chore: update repository name

biome.jsonc, package.json, packages/backend/package.json
PR includes:
- result of 'biome migrate` execution
- fixed format issues after migration
=> fix: biome migration issues

.github/workflows/bootc-e2e-nightly-windows.yaml
=> chore(test): fix typo

packages/backend/src/extension.ts
Skips initializing macadam on Windows, since the function is unused (no overlap in bootc and macadam between supported disk images). Also skips adding the provider and monitoring machines.
N/A
Fixes #1970.
PR checks pass; no regressions on Windows but macadam isn't installed.
=> chore: avoid initializing macadam on windows
