- package.json
Update workable badges / icons
Since the upstream changes have changed paramters (example, we use
'label' instead of 'name'), I've updated bootc for it to work.
Depends on: https://github.com/containers/podman-desktop/pull/5557
> Update workable badges / icons

- src/extension.ts
Improves the quick pick items, adding detail for each. I didn't use the description attribute b/c the layout is slightly off (another PF removal impact?) and to me it is easier to read like this.
Fixes #49.
> feat: improve quick pick formatting

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/epic.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Adds issue and PR templates. Almost identical to what we have in Podman Desktop, just removed one option that didn't apply, removed releases, and changed a reference or two from Podman Desktop to this extension.
Part of #24.
> feat: add issue templates

- src/build-disk-image.ts
nit: fix saying qcow2 not qemu
Small fix as the CLI type is qcow2 not qemu
N/A
N/A
You should be able to select qcow2 now without it erroring
> nit: fix saying qcow2 not qemu

- src/build-disk-image.ts
- src/constants.ts
- src/container-utils.spec.ts
- src/container-utils.ts
feat: add erroring out / refactor / add tests
* Checks to see if the image has actually errored out before continuing
* Moves the "container utility" functions to a separate file
* Adds a lot more tests
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/38
1. Start a build image
2. Stop the container during the build process.
3. It will fail as the container image will exit with error (1), rather
than saying success
> feat: add erroring out / refactor / add tests

- src/build-disk-image.ts
- src/extension.ts
- src/history.spec.ts
- src/history.ts
Saves the image, type, and folder for every image build. For today, this just lets us remember the history of image build folders and default to the same folder the next time you build.
Why save more than the last folder, and why save the image name and type too? There is no registry of past disk images (like we have with container images, or containers), e.g. they aren't saved to an OCI registry. Although there's some initial discussion to do this, there no timeline.
Saving this data means we have a list of all past images and at least some options for providing actions on them, e.g. launching vfkit from the (container) image instead of just from the ephemeral container that was used to build it. Including the data in this PR means we don't need to deal with an imminent breaking format …
> feat: remember image build history

- src/build-disk-image.ts
The build log is a lot of volume, and you can see it live in the containers view or stored after in our log file, so stop writing it to the console log as well.
N/A
N/A
N/A
> chore: stopping build log in console

- src/build-disk-image.ts
Adds a header to build logs so that you can see what version of the image builder was used and what the container args are.
```
Build Image Log --------
Image:  quay.io/deboer/bootc
Type:   raw
Folder: /Users/deboer/bootc
----------
{
"name": "bootc-bootc-image-builder",
"Image": "quay.io/centos-bootc/bootc-image-builder:latest-1705709685",
"Tty": true,
"HostConfig": {
"Privileged": true,
"SecurityOpt": [
"label=type:unconfined_t"
],
"Binds": [
"/Users/deboer/bootc:/tmp/"
]
},
"Labels": {
"bootc.image.builder": "true",
"bootc.build.image.location": "/Users/deboer/bootc/image/disk.raw",
"bootc.build.type": "ami"
},
"Cmd": [
"quay.io/deboer/bootc",
"--type",
"ami",
"--output",
"/tmp/"
]
}
----------
```
Fixes #85.
Do a build, look at the log.
> feat: add header to build logs

- src/build-disk-image.spec.ts
- src/build-disk-image.ts
Listing as a chore on our end, although I think we're confirming that the image builder really doesn't like writing to /tmp on some machines and that is causing builds to fail (but only when paired with certain output folders).
N/A
Fixes #86.
Test any build.
> fix: change output folder

- src/build-disk-image.ts
- src/machine-utils.spec.ts
- src/machine-utils.ts
feat: check for rootful before doing command
* Makes sure that the podman machine is actually rootful before
continuing
* Checks via the podman machine info json for rootful status.
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/d961aa94-0b29-45b6-880e-8b5703471d5c
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/17
1. Start a podman machine as rootless
2. See the error
3. Create another machine thats rootful
4. No error
> feat: check for rootful before doing command

- .github/workflows/build-next.yaml
Our CI shouldn't push the latest changes on main to :latest, because then anyone who pulls our latest container image will get the latest, unreleased code. Ideally, they should get the 'latest release'.
This changes the CI to push to :nightly. For the record I don't love the term 'nightly' and I don't think it's quite correct, but it is what AI Studio is using and I think it's better to be consistent. :)
N/A
Fixes #96.
Minor enough change, we can confirm when this PR is merged.
> chore: CI shouldn't use latest

- package.json
chore: remove vfkit from package.json
Removes vfkit from package.json (for now) until we explore more stable
options / stability issues with it.
Right now we should be informing the user how to launch it via docs
instead.
N/A
N/A
Buttons should no longer be there.
> chore: remove vfkit from package.json

- .github/workflows/release.yaml
Adds a release build action in Github that should tag and create the release, create a PR to bump the version, build and publish the bits.
Copied almost verbatim from @benoitf's work on the Minikube extension.
N/A
See below, issue #97 will be fixed but I don't want to trigger immediate closure here.
The normal way to test would be to copy the repo and test publishing to a private org, but this is fairly onerous, this is tested code from another repo, and failure isn't really going to affect anyone - so suggesting we merge, try it out, and rapidly fix if necessary.
> feat: release build

- src/build-disk-image.ts
chore: remove temporary ami fix
The latest release of bootc-image-builder now has raw support.
Remove the temporary fix for "ami" being "raw".
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/106
You'll be able to build raw normally without it appearing as "ami"
> chore: remove temporary fix

- .github/workflows/release.yaml
Copy paste error - the PR that the bot opens says:
```
Bump version to 0.2.0
has been released.
```
when it should include the version that was released (0.1.0 in this case) in the second line.
N/A
N/A
Wait for next release.
> chore: fix version update PR description

- .github/workflows/release.yaml
The 'tag' release job was setting the correct version in package.json, then bumping it up to create a PR and doing the build, which means the output container has the bumped version and not the release version.
Looked at other options, but the tasks don't appear to depend on each other so I'm just swapping the order.
N/A
Fixes #116.
Just logic review, till need to wait for next release.
> chore: update release version

- package.json
bootc extension is published as `redhat.bootc` in the catalog so it should match the name of the package.json as well
or we change the catalog to use `redhat.bootc-extension`
so when installing the extension we're not finding the right extension after so some buttons are not replaced/ arestill in progress/etc
https://github.com/containers/podman-desktop/issues/5759
> fix: change name

- package.json
There's an official label for bootable containers: containers.bootc. Adds support for this without removing the previous label for now, so that we don't have any release where only one path works. Once the new label is prevalent we'll remove the old one.
N/A (badge and icon work as before)
First part of #129; will remove old label later.
Manually label an image with containers.bootc and confirm badge, icon, and actions still appear.
> feat: support new container label

- src/build-disk-image.spec.ts
- src/build-disk-image.ts
Make sure we pick an unused container name so that it's possible to kick off multiple builds at the same time.
Note that there are still two theoretical places this could still fail due to the delay between when you kick off the task and we check for conflicts vs when the container gets created: the first time you ever run (if the bootc builder image takes time to pull down) and if you're super-fast and run the action twice before the container engine can create a container and register back in Podman Desktop. The first seems very unlikely that someone would try, and the second I couldn't even reproduce when trying.
Fixes #103.
Run two builds at the same time, confirm no name conflict and both images are produced.
> fix: pick unused container name

- docs/containerfile_guide.md
- examples/bootc-helloworld-python-systemd/Containerfile
docs: update readme systemd files
The centos bootc image now allows using `systemctl enable`
See: https://github.com/CentOS/centos-bootc/issues/167
N/A
N/A
N/A
> docs: update readme systemd files

- src/build-disk-image.ts
- src/container-utils.spec.ts
- src/container-utils.ts
Adds a new function to delete images with a given name that do not have the same tag (nor a second tag; you can tag to keep something). Uses this to look for and clean up any old builder images, so that we'll automatically clean up whenever we pull a new one.
N/A
Fixes #98.
Pull the 'latest' bootc builder image and then build a new disk image, 'latest' will be deleted since we're using a tagged one.
> feat: remove old builder images

- src/build-disk-image.spec.ts
- src/build-disk-image.ts
- src/constants.ts
Step up to the latest image builder, and adds support for the new --target-arch parameter, which supports building arm64 and amd64 disk images.
Fixes #28.
Build an image with both architectures.
> feat: multi-arch support

- .eslintrc.json
- packages/backend/tsconfig.json
chore: enable prefer nullish for eslint
Enables prefer `??` over `||` for eslint
N/A
N/A
run `yarn lint:fix`
> chore: enable prefer nullish for eslint

- packages/backend/src/build-disk-image.ts
- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
chore: fix rootful mode for podman 5.0.0 / enables linux check
* Enables being able to test against podman 5.0.0
* Re-enables the Linux check now that you can create a podman machine on
Linux
N/A. You should be able to build like normal.
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/167
1. Test against Podman 5.0.0
2. Be able to build an image like usual.
> chore: fix rootful mode for podman 5.0.0 / enables linux check

- packages/backend/src/build-disk-image.ts
- packages/backend/src/extension.ts
- packages/backend/src/history.spec.ts
- packages/backend/src/history.ts
- packages/backend/src/quickpicks.spec.ts
- packages/backend/src/quickpicks.ts
- packages/shared/src/models/bootc.ts
- packages/shared/tsconfig.json
- packages/shared/vite.config.js
- packages/shared/vitest.config.js
feat: refactor of build logic / more history info / quickpicks
In order to add the "quickpick" logic in a separate file, it was
beneficial to also refactor what history information we also save.
In this PR we:
* Separate the "quickpick" functionality into a separate file, so we may
use the build disk image function separately
* Additional history information being saved such as build container id,
timestamp, etc.
N/A, internal only. Build functionality should work as intended.
Closes #173
Closes #174
Build a disk image, it should continue as normal.
Check:
`~/.local/share/containers/podman-desktop/extensions-storage/redhat.bootc/history.json`
for the 'updated history info'
> feat: refactor of build logic / more history info / quickpicks

- README.md
docs: update docs regarding Linux and 5.0.0
In order to use this extension, we require 5.0.0 as below that version
is very unstable.
Linux is also now supported with being able to create a rootful Podman Machine
on Podman Desktop.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/93
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/140
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/185
N/A
> docs: update docs regarding Linux and 5.0.0

- docs/vm_guide.md
docs: Add note regarding arm64 testing using vfkit
Adds note regarding applehv only running arm64 images.
N/A
References https://github.com/containers/podman-desktop-extension-bootc/issues/184
> docs: Add note regarding arm64 testing using vfkit

- README.md
docs: Add more details regarding Linux podman machine
Adds some more details regarding rootful mode on Linux with podman
machine. Since you cannot create the machine through the podman desktop
GUI, you must create it via the command line.
N/A
References #93
N/A
> docs: Add more details regarding Linux podman machine

- packages/backend/src/container-utils.spec.ts
- packages/backend/src/container-utils.ts
chore: improves timeout of waitForContainer
* Adds a long timeout (30 minutes) for waiting for the container to
build
* Adds retries in case the container dissapears
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/194
Covered by tests
> chore: improves timeout of waitForContainer

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/constants.ts
- packages/frontend/src/Build.svelte
The Bootc image builder added support to build from local storage via https://github.com/osbuild/bootc-image-builder/issues/90.
This updates to the current bootc image builder image, and adds the two new required options:
- --local, should be temporary/default soon
- volume mapping to /var/lib/containers/storage
N/A
Fixes #178.
Test updated.
> feat: build from local storage

- packages/backend/src/build-disk-image.ts
Write the log files to disk as we get the data, instead of buffering and waiting until the end. This is better for debugging outside of Podman Desktop and will help in the future if we need to show logs in another view.
N/A
Fixes #78.
Build an image and open image-build.log before it is done.
> chore: dynamically write log files

- README.md
It's missing the `/packages/backend` to be picked up by `yarn watch`.
> README: fix `yarn watch`

- .github/workflows/e2e-main.yaml
Introduces E2E test workflow to be run on main branch merge and on demand.
Update: It can also run different fork/repoName/branch using GHA workflow inputs.
#210
> chore(ci): add a workflow that executes e2e tests

- packages/backend/src/build-disk-image.ts
- packages/backend/src/quickpicks.spec.ts
- packages/backend/src/quickpicks.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
feat: add vmdk option
Adds the VMDK option for buildin.
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/183
1. Test using the httpd example container
2. Build the vmdk
3. Run in on your favourite vmdk software
> feat: add vmdk option

- .github/workflows/pr-check.yaml
- packages/frontend/package.json
- yarn.lock
chore: fix typecheck
* `import '@testing-library/jest-dom/vitest';` was not properly added
and was giving typecheck errors when trying to run `yarn typecheck` on
a fresh install
* added typecheck to github workflow
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/225
Run `yarn typecheck` should receive no errors / warnings now.
> chore: fix typecheck

- packages/backend/src/extension.ts
The webview wasn't registered as a subscription, so it wasn't cleaned up when the extension is stopped.
N/A
Fixes #227.
Go to Settings > Extensions and stop/start the extension. Prior to the fix the webview would be registered multiple times.
> fix: register webview for disposal

- packages/frontend/src/App.svelte
- packages/frontend/src/Build.svelte
- packages/frontend/src/lib/NoBootcImagesEmptyScreen.spec.ts
- packages/frontend/src/lib/NoBootcImagesEmptyScreen.svelte
- packages/frontend/src/lib/upstream/stores/breadcrumb.ts
nit: fix naming to match extension
Fixes the naming BootC to Bootable Container like the rest of the
extension.
This includes any breadcrumbs as well.
N/A
Build / view the pages.
> nit: fix naming to match extension

- Containerfile
- package.json
- packages/backend/package.json
- packages/frontend/package.json
- yarn.lock
Update the version of Podman Desktop we depend on to 1.8, and align on a single ui-svelte package (currently there are two different versions in frontend/package.json).
N/A
N/A
Just regular build tests.
> chore: update PD dependency

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/extension.ts
- packages/backend/src/history.spec.ts
- packages/backend/src/history.ts
- packages/backend/src/quickpicks.spec.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/src/Homepage.spec.ts
- packages/frontend/src/Homepage.svelte
- packages/frontend/src/lib/BootcActions.spec.ts
- packages/frontend/src/lib/BootcColumnActions.spec.ts
- packages/frontend/src/lib/BootcFolderColumn.spec.ts
- packages/frontend/src/lib/BootcImageColumn.spec.ts
- packages/frontend/src/lib/BootcImageColumn.svelte
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/bootc.ts
chore: create unique entries in history when building
* Instead of overriding the previous history, create a unique entry
using name
* Adds 'name' to the interface
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/dc2ba8f1-a04b-4219-8edc-0777b45eabf1
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/201
1. Delete `rm
~/.local/share/containers/podman-desktop/extensions-storage/redhat.bootc/history.json`
2. Create multiple builds, they should appear now as multiple builds.
> chore: create unique entries in history when building

- packages/backend/src/api-impl.ts
- packages/backend/src/extension.ts
- packages/shared/src/BootcAPI.ts
- packages/shared/src/messages/Messages.ts
chore: expose pull image API
* Adds pull image API for the frontend to use
* Adds notify to api-impl.ts for the frontend to be able to push updates
N/A
References https://github.com/containers/podman-desktop-extension-bootc/issues/150
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/237
Use `bootcClient.pullImage("quay.io/your/test/image");` within the code
> chore: expose pull image API

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
Image builder has had an issue for a while now where if you specify the target arch when building an iso it will fail, even if you're specifying the current/default arch. We've had enough users hit this (so this extension is the 'blocking' issue) even though the generated images are also broken/unusable.
We've discussed possible UI changes (like having a 'no target arch' option, or allowing no arch to be selected) but we don't really like these and do not want to make UI changes that could be very temporary - so this is the simplest workaround for now that will unblock users.
Once the following bug is resolved we will update image builder, remove this workaround, and if necessary change the UI.
https://github.com/osbuild/bootc-image-builder/issues/316
N/A
Temporary fix for #149.
Build an …
> chore: temporarily ignore arch when building iso

- packages/backend/src/build-disk-image.ts
Every single time someone says "image" in contexts like this I will stop them and make them clarify, are they talking about a "disk image" or a "container image" - they're different things!
This message seems to imply a *container* was created.  No, the container was already made.  What we're doing here is generating a disk image.
(Also, "in" makes more sense than "to" when talking about folders)
> build-disk: Clarify output message

- README.md
- The root password I think is dangerous *especially* for anything involving uploading an AMI etc.  As the comment says it's only not catastrophic because of `PermitRootLogin prohibit-password` in our default images.  To really make this better we need to streamline the "launch with local virt" flow, which I think is best done with integration with podman-bootc which needs further work.
- Emphasize the difference between disk images and container images across the board more
- Link to new bootc generic docs on things like users/groups
- No need to use the `-dev` images
> chore(README): Root pw clarification, link other docs, drop -dev

- packages/backend/package.json
- packages/backend/src/build-disk-image.ts
- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
- yarn.lock
Provide a function to test if the machine we're running on is Podman v5 or higher, and use it to trigger an error if we try running an image build on an older machine.
N/A
Fixes #168.
Automated tests; try running a build with a <5.0 machine.
> feat: error if running on older podman version

- packages/backend/package.json
Not sure how we missed following up, but support for customizing menu action icons was added to PD 1.8. This just sets it to our icon.
Fixes #44.
Just go to images view and ensure the menu action has an icon.
> chore: use bootc icon for menu

- packages/backend/package.json
- packages/backend/src/extension.spec.ts
- packages/backend/src/extension.ts
Idea and code shamelessly stolen from https://github.com/containers/podman-desktop-extension-ai-lab/pull/766 and https://github.com/containers/podman-desktop-extension-ai-lab/pull/778.
This code ensures that the extension is never run on an older Podman Desktop release.
N/A
Fixes #263.
Automated tests updated. Install on an older PD release and confirm extension will not load.
> chore: ensure podman desktop minimum version

- packages/backend/src/constants.ts
We last updated the image builder 2 weeks ago. This moves to the latest, which appears to have significant reduction in peak memory use, possibly negating the need for #221.
N/A
N/A
Regular automation, test building different image types.
> chore: update bootc-image-builder

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/container-utils.spec.ts
- packages/backend/src/container-utils.ts
- packages/backend/src/extension.ts
- packages/frontend/src/Homepage.spec.ts
- packages/frontend/src/Homepage.svelte
- packages/shared/src/BootcAPI.ts
Exposed the telemetry logger from the extension, and changed build-disk-image.ts to use it instead of its own. While doing this I noticed that logUsage was being called before and after the build, so I removed the first to avoid double-counting.
Adds telemetry event when pulling images. The intent here is to show how often users pull the example but will also trigger when pulling the image builder itself, which might also be useful.
Exposes telemetry logging to frontend, and sends an event when someone clicks on the button to go to the Build page.
N/A
Part of #179.
Tests added to confirm telemetry events. To test manually, enable telemetry and either watch live in Segment or modify PD telemetry to output to console.
> feat: add telemetry to pull, goto build page

- README.md
docs: update readme with proper image
It should be linking to quay.io/centos-bootc/centos-bootc as
fedora-bootc is the old one.
N/A
N/A
N/A
> docs: update readme with proper image

- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
fix: be able to test on 5.1.0-dev / dev 5.0.0 podman machine
* Ability to build on 5.1.0-dev builds.
* Added more tests and validation
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/b4de15d7-16b3-41d6-85ca-a7575dbf4450
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/291
1. Run 5.1.0-dev podman machine
2. Be able to build correctly
> fix: be able to test on 5.1.0-dev / dev 5.0.0 podman machine

- packages/frontend/src/Build.svelte
Need to use 1x instead of 16 in order to support Svelte 4. Unblocks dependabot PR #283.
N/A
Unblocks #283.
Confirm icon in image dropdown in Build page looks the same.
> chore: svelte 4 compliance

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
- packages/shared/src/BootcAPI.ts
Currently, there is no way for the frontend to check prereqs or see if there is an existing image before attempting to build, at which point the backend has to open dialogs to notify of an error, or ask the user whether to overwrite.
This PR moves the existing code from the build to check prereqs and for existing images out into two functions accessible to the frontend:
- checkPrereq() checks that the machine is Podman v5 and rootful.
- buildExists() checks if there's an existing build in a given folder.
It also adds an option to the build to overwrite an existing image.
Tests existed for the underlying function and the build just calls the refactored functions, so there is no behaviour change from before.
N/A
Refactoring in preparation for #200 and #262.
Existing PR checks and Build page …
> chore: expose validation API

- packages/backend/package.json
- packages/backend/src/container-utils.spec.ts
- packages/backend/src/container-utils.ts
- packages/backend/src/extension.ts
Makes the build timeout a configurable timeout in Settings > Preferences.
Adds a helper function in extension.ts for future configuration, and increases the default timeout to 30 minutes.
N/A
Fixes #315.
Create a really big image/slow your machine down, or set the timeout really low.
> chore: increase build timeout

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
I noticed during testing that the path where vmdk images are generated is wrong, or was changed at some point. We don't prompt to overwrite without this change.
At some point our E2E tests will be able to cover this.
N/A
N/A
Generate a vmdk build, then a second one. You won't be prompted to confirm overwriting before this change.
> chore: fix vmdk output folder

- packages/backend/src/api-impl.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
Prior to this change, if you were missing prereqs (v5+rootful) or were missing some option you wouldn't see a problem until you build, and then after you accepted the error message it would sit on the build screen for 10s before it timed out. Likewise, if there was an existing build and you said 'no' to overwriting, it would wait for 10s to time out.
With this change, all validation is done inside the form. If you're missing a prereq or one of the options, the error message is visible at the bottom of the form and the Build button is disabled until you fix it. If you need to confirm overwriting an existing build, a checkbox appears.
Renamed buildErrorMessage so it's more clear this is the post-build error.
Added tests for prereqs and overwriting, and fixed the rather obvious error in …
> feat: build form validation

- packages/frontend/src/Build.svelte
The first two titles had different styling than the others, this just makes them match.
Before:
After:
N/A
Open build page.
> chore: consistent titles

- packages/frontend/src/Build.svelte
nit: make red colouring less bright
It's hurting my sensitive eyeballs.
I find the bright red very distracting and it'd be good to have it
darker similar to PD.
New:
Old:
N/A
Preview the UI
> nit: make red colouring less bright

- packages/frontend/src/Build.svelte
chore: update terminology, reorder platform
* Updates the terminology on the build page
* Re-orders the platform so it matches how it's ordered in PD (arm
first, then AMD second)
N/A, just view the .svelte code
N/A
N/A
> chore: update terminology, reorder platform

- packages/backend/src/api-impl.ts
- packages/backend/src/container-utils.spec.ts
- packages/backend/src/container-utils.ts
- packages/shared/src/BootcAPI.ts
chore: add inspectImage API
Adds the inspectImage API for the frontend so that we can inspect the
image for the architecture / OS / more information before building.
Part of https://github.com/containers/podman-desktop-extension-bootc/issues/245
N/A
Part of https://github.com/containers/podman-desktop-extension-bootc/issues/245
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/339
Covered by tests
> chore: add inspectImage API

- packages/backend/package.json
- packages/backend/src/api-impl.ts
- packages/backend/src/container-utils.spec.ts
- packages/backend/src/container-utils.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/lib/BootcEmptyScreen.spec.ts
- packages/shared/src/BootcAPI.ts
- yarn.lock
feat: add inspectManifest endpoint to api
* Adds the inspectManifest endpoint to the API
* Requires https://github.com/containers/podman-desktop/pull/6812 to go in
first
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/340
Use the `inspectManifest` endpoint with a passed in image.
> feat: add inspectManifest endpoint to api

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
feature: automatically select image based on image architecture inspect
* Automatically selects the image based upon what architecture is
available under inspect image.
Note that this is also in anticipation of manifest feature being added,
so there is some code in here (such as an array, rather than a single
string) for manifest.
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/2d09c5c5-6164-4811-89c0-e17e813608ae
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/245
Open a build, try and click on arm64 / amd64.
> feature: automatically select image based on image architecture inspect

- packages/frontend/src/Build.svelte
- packages/frontend/src/Homepage.svelte
- packages/frontend/src/lib/DiskImageIcon.svelte
This is minor, but we have a nice icon and the PD standard is more typically to use the icon for the thing you want to create (i.e. a disk image) not the thing you have now (container image). We didn't have the 'correct' container image anyway since it is not exported from PD, yet another reason to use the disk image icon.
Changes the default disk image icon to be solid and the correct size for buttons, then uses it for the homepage button, and a larger version for the Build page.
N/A, just cleanup chore.
Go to homepage, build page.
> chore: use disk image icon for build

- packages/backend/src/extension.spec.ts
- packages/backend/src/extension.ts
I noticed that AI lab is doing this - send the extension version in on startup so that we can see which version users have installed. This should also be in the PD telemetry, but easier to track/correlate here.
N/A
N/A
Test updated.
> chore: send telemetry on startup

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
Bootc image builder does not support cross-arch building of ISO images for now: https://github.com/osbuild/bootc-image-builder/issues/316
However, there was an issue where it would fail if you specify a target arch, even if that's the current one. This has been fixed and is in the bib that we currently depend on: https://github.com/osbuild/bootc-image-builder/pull/364
This removes the workaround we had in place to avoid ISO builds failing.
N/A
Fixes #269.
Unit test updated. Build any iso to confirm it now works.
> chore: remove bib iso target workaround

- docs/vm_guide.md
docs: add port forwarding for testing
* Fixes up the order of the commands
* Adds notes / information about using port forwarding on the qemu
commands
N/A
N/A
Run the command after build an arm64 image, specifically the test image, and curl the 8080 port.
> docs: add port forwarding for testing

- packages/frontend/src/Build.svelte
Just a little thing I noticed this morning, after clicking Build we should show the Disk Image icon, not rocket.
Fixes #390.
Build an image.
> chore: use disk image after starting build

- packages/frontend/tailwind.config.cjs
Fixes the import of svelte components from 3rd party library
fixes https://github.com/containers/podman-desktop-extension-bootc/issues/292
> fix: make correct import of Podman Desktop ui svelte library

- packages/frontend/tailwind.config.cjs
it's only used in the website of Podman Desktop so it makes the UI not consistent with Podman Desktop
Pages of bootc extension will look more similar than Podman Desktop core
> fix: remove the usage of the MontSerrat font

- packages/backend/src/api-impl.ts
- packages/backend/src/constants.ts
- packages/backend/src/container-utils.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
feat: add manifest / multi-arch selection support
* Manifests are now listed, inspected and propagated within the Build
page
* Simply select a manifest, select the arch and it will build
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/5a2c32a2-cddc-4180-9758-c7512d48bbf8
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/324
Follow the video above, or do the following tests:
1. Build a manifest within Podman Desktop (select two architectures, and
build a bootc image). Must use the latest Podman Desktop
2. Select the manifest within the extension and see it build.
> feat: add manifest / multi-arch selection support

- Containerfile
Our startup check would block use on wrong version of Podman Desktop anyway, but best to keep all metadata in sync and now clearly depending on 1.10.
N/A
Fixes #404.
Just PR checks for now.
> chore: update containerfile

- packages/backend/src/constants.ts
chore: update bootc-image-builder (includes iso fix)
Updates to the newest bib image which includes the ISO fix: https://github.com/osbuild/bootc-image-builder/issues/404
N/A
https://github.com/osbuild/bootc-image-builder/issues/404
You can test this by building a manifest, then selecting an iso (amd64
or arm64) and booting it with your favourite VM manager.
> chore: update bootc-image-builder (includes iso fix)

- packages/backend/src/constants.ts
chore: update bib to include --rootfs parameter
Updates bib to include the --rootfs parameter
N/A
Related to https://github.com/containers/podman-desktop-extension-bootc/pull/434
you should be able to build perfectly normal
> chore: update bib to include --rootfs parameter

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/constants.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/models/bootc.ts
feat: add ability to select default, xfs and ext4 filesystem
* Ability to select the filesystem by either picking default (which will
use the container's default), xfs or ext4.
* Updates the bootc-image-builder image to support rootfs
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/433
Normal testing:
1. Go through all the normal build scenarios (build manifest, etc) and
select the either default, xfs or ext4.
Testing Fedora:
1. Pull `quay.io/fedora/fedora-bootc:40`
2. Build `quay.io/fedora/fedora-bootc:40` and select "default" it should
fail.
3. Build `quay.io/fedora/fedora-bootc:40` and select "xfs" or "ext4" and
it should build.
> feat: add ability to select default, xfs and ext4 filesystem

- README.md
docs: update README since tables does not render correctly
- Updates the README since tables to do not render correctly in podman
desktop extensions page
- Adds links to source pages of the images
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/447
References https://github.com/containers/podman-desktop/issues/7112
N/A, look at docs
> docs: update README since tables does not render correctly

- README.md
docs: add rhel to list, update fedora links
* Adds RHEL to the list
* Updates the fedora links to the new repo
N/A
Closes https://github.com/containers/podman-desktop-internal/issues/254
N/A
> docs: add rhel to list, update fedora links

- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
- requires to update ubuntu runner to 24.04 beta
Installs podman v5 on ubuntu 2404 beta runner in workflows that runs e2e tests.
#478 
you can run the changes in your fork (main branch).
> chore(ci): update podman to version 5 for e2e test workflows

- packages/backend/src/api-impl.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/BootcAPI.ts
feature: detect fedora image and update filesystem
* Detects if the base image is based upon fedora
* If it is based on fedora, auto-select the filesystem
https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/4f82f815-85e9-4b51-91c0-bea27700dbd1
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/457
Select a fedora bootc image or manifest, it will auto-select XFS.
If you select a non-fedora bootc image, it will be default.
Tests also cover new feature
> feature: detect fedora image and update filesystem

- .github/workflows/bootc-e2e-nightly-windows.yaml
Add nightly/on demand workflow to run bootc e2e tests on windows
https://github.com/containers/podman-desktop-e2e/issues/172
It would require adding scepcial credentials into repo. TBD
> chore(ci,tests): add workflow to run bootc e2e tests on windows

- README.md
The "source" link for centos-bootc changed; just drop it, as I'd like to have the documentation be canonical.
(Now of course hopefully we aren't going to go through a round
of moving things *again* any time in the near future, but still
I think users should click through to the docs site as
a general rule)
> README.md: Trim links a bit

- tests/playwright/src/bootc-extension.spec.ts
Refactors bootc e2e tests to call exposed method from test framework
https://github.com/containers/podman-desktop-extension-bootc/issues/526
> chore(test): refactor to use exposed method

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/BootcEmptyScreen.svelte
- packages/frontend/src/lib/BootcImageColumn.svelte
feat: add initial light mode for homepage & dashboard
Adds initial light mode for the homepage and dashboard (column colour
changes).
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/539
Visit homepage and dashboard and see light mode works fine
> feat: add initial light mode for homepage & dashboard

- packages/frontend/src/lib/BootcFolderColumn.svelte
- packages/frontend/src/lib/BootcImageColumn.svelte
We did this in Podman Desktop but should do it in bootc - text columns that can be too wide should use ellipsis.
The new bootc Link component (on PD Link component) supports opening folders directly, so we can remove the unused import and function. Added color variable so that ellipsis is grey instead of white.
Before:
After:
Fixes #549.
Do a build, make the window narrow.
> chore: use ellipsis in columns

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
The temporary checkbox had some minor UI issues, time to use the Checkbox component from Podman Desktop UI library. There is a limitation that you cannot bind to a group array with a value that would have made this particular case a little simpler, but I just used a function that updates the buildType array.
Before:
After:
Fixes #537 (and also required for light mode #540).
Use the build form.
> chore: adopt checkbox component

- packages/frontend/src/Build.svelte
I wasn't seeing this while testing #576, but it must have been there in some form.
The fix is simple: validation isn't being triggered when the contents of the buildType array change, so just trigger it directly instead of relying on svelte reactivity.
N/A
Fixes #584.
Enable/disable various build types.
> fix: build type validation

- packages/frontend/index.html
- packages/frontend/package.json
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/src/lib/BootcStatusIcon.svelte
- yarn.lock
Move up to latest ui-svelte in order to do the following. Requires a recent Podman Desktop build in order for variables to be defined at runtime.
In the Build form, pick up status colors, switch to use ErrorMessage component, and pick up other light mode color variables. Uses the same styling as PD for the tiles, and radio buttons use the checkbox color variables (since PD has no vars for radio inputs).
Use status colors in bootc status icon for now - we should probably reuse StatusIcon now, but that's separate work.
After doing this, we can even set the default text color in the index.
Not marking this as 'fixes' since we still need a select component, but this is most of #540.
Check the homepage and build page in light and dark modes.
> chore: light mode, mostly for build page

- package.json
- yarn.lock
chore: fix build issue
See: https://github.com/yarnpkg/yarn/issues/8994#issuecomment-2207025146
TLDR; Issues with string-width depdendencies requires us to pin the
versioning for string-width and wrap-ansi since it's using two of the
same module.
N/A
N/A, on slack.
Tests should pass / `yarn watch` and `yarn build` should work.
> chore: fix build issue

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/bootc.ts
feat: be able to use build config
* Under advanced have build config file option
* Be able to pass in YAML or JSON file
* Misc: Fixes size of font for AWS options
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/471
1. Use our test bootc image
2. Create a TOML file with the following:
```
[[customizations.user]]
name = "root"
password = "letmein"
```
3. Build image
4. Confirm you can login
5. Test again with a JSON file:
```
{
"customizations": {
"user": [
{
"name": "root",
"password": "letmein2"
}
]
}
}
```
> feat: be able to use build config

- packages/frontend/index.html
- packages/frontend/package.json
- packages/frontend/src/Build.svelte
- packages/frontend/src/lib/BootcEmptyScreen.svelte
- packages/frontend/src/lib/BootcFolderColumn.svelte
- packages/frontend/src/lib/BootcImageColumn.svelte
- packages/frontend/tailwind.config.cjs
- yarn.lock
Match up with the new font sizes / consistency as Podman Desktop:
- Pick up the latest svelte-ui (changes to input/button font).
- Set the same font sizes as Podman Desktop.
- Set the default font size in index.html.
- Make equivalent size changes in Homepage and Build page - mostly removing text-sm or moving from -xs to -sm.
Before:
After:
Fixes #625.
Go to homepage and build page.
> chore: font size and consistency

- packages/frontend/tailwind.config.cjs
The bootc extension tailwind config was originally copied from Podman Desktop and contains a lot of unused content. We should remove all of it so stay right-sized, so that it's obvious which colors are still hard-coded (should probably be using color variables), and so that we don't add any new dependency on colors.
N/A
Fixes #627.
PR checks should pass, check UI for regressions.
> chore: tailwind cleanup

- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-page.ts
Fixes a bug where the e2e test moves on before the latest build triggered is displayed on bootc page
https://github.com/containers/podman-desktop-extension-bootc/issues/629
> chore(test): wait for list to update in build page

- .github/dependabot.yml
Same change as https://github.com/containers/podman-desktop/pull/8122, makes fortawesome dependabot updates a single issue instead of many.
N/A
N/A
N/A
> chore: reduce dependabot FA issues

- tests/playwright/src/bootc-extension.spec.ts
Removes bootc images from e2e tests at the end of the test.
https://github.com/containers/podman-desktop-extension-bootc/issues/659
> chore(test): remove bootc images before finishing

- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-page.ts
Increases waiting timeout for build finishing before it takes much longer on windows
https://github.com/containers/podman-desktop-extension-bootc/issues/629
> chore(test): increasing timeout for windows

- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-page.ts
Adds a special flag to build ISO images and increases timeout in such a case, because ISO builds take much longer than others.
https://github.com/containers/podman-desktop-extension-bootc/issues/662
> chore(test): special handling for iso builds

- tests/playwright/src/bootc-extension.spec.ts
Checks for initial image build to be finished correctly before trying to use the image afterwards.
https://github.com/containers/podman-desktop-extension-bootc/issues/675
> chore(test): skip tests if image build failed

- tests/playwright/src/bootc-extension.spec.ts
Increases timeout for waiting on build finish due to slow build time on azure machines
https://github.com/containers/podman-desktop-extension-bootc/issues/690
> chore(test): increasing timeout for windows e2e tests

- tests/playwright/src/bootc-extension.spec.ts
Adjusts timeout in afterAll hook of e2e tests
https://github.com/containers/podman-desktop-extension-bootc/pull/689
> chore(test): adjusting timeout in afterAll hook

- README.md
- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/history.spec.ts
- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/src/Homepage.spec.ts
- packages/frontend/src/lib/BootcActions.spec.ts
- packages/frontend/src/lib/BootcColumnActions.spec.ts
- packages/frontend/src/lib/BootcFolderColumn.spec.ts
- packages/frontend/src/lib/BootcImageColumn.spec.ts
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/bootc.ts
feat: use native podman build for linux
* Switches to using native podman building for Linux rather than using
podman machine
* Tested against using a manifest as well as a normal image.
* Uses CLI commands the equivalant of doing `sudo podman run`. PD does
not support running / viewing / using sudo root connections. So we use
the CLI instead
* Uses CLI commands for saving the image / importing as well. The
reasoning is that importing requires `sudo` / privileged and
retrieving via image ID does not work for saving via the API.
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/623
1. Try on Linux (Fedora 40 or above)
2. Go to build and it should ask for credentials after a few moments of
building
3. Successful image build
Signed-off-by: Charlie Drage …
> feat: use native podman build for linux

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/backend/src/machine-utils.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/bootc.ts
feat: add chown (linux only)
* Adds chown to the advanced settings page for build
* Only applicable to Linux (see:
https://github.com/osbuild/bootc-image-builder/issues/576)
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/472
1. Be on Linux
2. Build an image
3. See that it is chown (ex. ls -l /outputdir)
> feat: add chown (linux only)

- tests/playwright/package.json
- tests/playwright/playwright.config.ts
- tests/playwright/src/bootc-extension.spec.ts
Migrates bootc e2e tests to playwright test runner.
https://github.com/containers/podman-desktop-extension-bootc/issues/781
> chore(test): migrate tests to pw runner

- packages/backend/src/build-disk-image.ts
chore: add debugging / error information to log file as well
Adds some simple code that also outputs any errors with the function to
the log file for debugging purposes / being able to help for any
debugging.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/678
1. Before pressing build, stop your Podman Machine
2. See that it outputs the connection error into the build log file.
> chore: add debugging / error information to log file as well

- README.md
- docs/vm_guide.md
- packages/backend/src/build-disk-image.ts
- packages/backend/src/constants.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/models/bootc.ts
- tests/playwright/src/bootc-extension.spec.ts
feat: add vhd option
* Adds option for vhd / vpc images to be used on Hyper-V or Azure
https://github.com/user-attachments/assets/a88f32f8-8037-4564-8af6-3e5759fe1b1a
https://github.com/user-attachments/assets/ab2004ac-ad83-49f5-a0a2-e3aaf8425717
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/799
1. Build a vhd
2. See it completes build correctly.
3. Launch via Hyper-V or Azure / other software
> feat: add vhd option

- packages/backend/package.json
- packages/backend/src/api-impl.ts
- packages/frontend/src/App.svelte
- packages/frontend/src/Logs.spec.ts
- packages/frontend/src/Logs.svelte
- packages/frontend/src/lib/BootcActions.spec.ts
- packages/frontend/src/lib/BootcActions.svelte
- packages/frontend/src/lib/upstream/terminal-theme.ts
- packages/shared/src/BootcAPI.ts
- yarn.lock
feat: adds log page for builds
* Adds a log action button that will show the logs in real-time in a
separate page
* Automatically refreshes / appends to the output
* Uses terminal settings from Podman Desktop to match what the user has
setup.
https://github.com/user-attachments/assets/d440a86a-dee7-46cf-9aef-84aa1e3298d9
https://github.com/user-attachments/assets/05d6b51f-80c3-4717-8b40-dff1df61ea49
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/677
1. Start a build
2. Click the "logs" button on the dashboard
3. Watch logs propagate
> feat: adds log page for builds

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
chore: add iso validation when building
* Adds validation that checks if anaconda-iso and another type has been
selected, and errors out / shows a warning
https://github.com/user-attachments/assets/be31131c-1031-4e52-8800-1eac5572990c
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/702
Try to select iso while another is selected (qcow2, iso, etc.)
> chore: add iso validation when building

- package.json
- packages/frontend/package.json
- pnpm-lock.yaml
Removes svelte/svelte-check from the root workspace, as it should only be a frontend dependency.
N/A
N/A
PR build.
> chore: svelte should only be in frontend

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/BootcActions.spec.ts
- packages/frontend/src/lib/BootcActions.svelte
- packages/frontend/src/lib/BootcImageColumn.spec.ts
- packages/frontend/src/lib/BootcImageColumn.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetails.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsSummary.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsSummary.svelte
- packages/frontend/src/lib/upstream/DetailsCell.svelte
- packages/frontend/src/lib/upstream/DetailsTable.svelte
- packages/frontend/src/lib/upstream/DetailsTitle.svelte
- packages/frontend/src/lib/upstream/Util.spec.ts
- packages/frontend/src/lib/upstream/Util.ts
Modifies the build logs to have a proper details page for disk images, similar to how Podman Desktop handles Images or Containers.
The two tabs are Summary and Build Logs. The summary page is simple for now but could be expanded; the build logs doesn't really match what we typically have in Podman Desktop, but it fits in better here than a standalone page.
Before:
https://github.com/user-attachments/assets/1b6f3788-b3b2-49e3-8798-94bf19da9d19
After:
https://github.com/user-attachments/assets/8069ea15-bb7a-42b8-a86a-1fcd6655e576
Fixes #856.
Build some disk images, switch between homepage and disk image, use homepage action to go straight to a build.
> feat: details page for disk images

- packages/frontend/src/Build.svelte
chore: fix links on build page
We were incorrectly using Links from the UI which unfortunatley does not
work (does extra call to external link).
Use `Link` that we've been using in the empty page, etc.
https://github.com/user-attachments/assets/4c2969d2-31ec-45c8-9983-616eff735309
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/910
Links on build page work now.
> chore: fix links on build page

- packages/frontend/tailwind.config.cjs
After a hint from @axel7083 I noticed the bootc frontend Tailwind config is dependent on source in ui-svelte, which is no longer there in recent builds. Switch to dist instead.
Before: missing colors, css.
After: same as before.
Fixes #907.
Check main page looks normal again.
> fix: missing component styling

- packages/backend/src/api-impl.ts
- packages/backend/src/history/historyNotifier.spec.ts
- packages/backend/src/history/historyNotifier.ts
Confirmed the error isn't impacting function at all, but use an empty object instead of an empty string to avoid errors in the log.
The code in api-impl.ts had an optional parameter that was always passed, just make the parameter mandatory to avoid the same problem in the future.
N/A
Fixes #914.
PR checks, or try creating/deleting builds and make sure the notifier error is no longer in the logs.
> chore: always pass empty body to notify message

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
When a build is started successfully, go directly to the build logs.
Switches to use the store instead of calling bootcClient.listHistoryInfo() repeatedly, less for performance/reuse and more to ensure that the store has been updated before switching to the build logs. Otherwise we may try to switch before the store has been updated.
Noticed a pattern in a few other tests of clicking and then 'await new Promise', fixed these to await the userEvent while I was here.
https://github.com/user-attachments/assets/5c392ef0-e522-4d8b-978a-4e8e791ab0a2
Fixes #872.
Start a build and make sure it automatically switches to the Build Logs instead of the previous page.
> feat: go directly to build logs on successful build

- README.md
docs: add known issue cross-arch building
* Adds documentation regarding cross-arch building
* Docs are meant as an intermediary until podman machine is patched with
the new QEMU calls
* When QEMU is patched, the only thing needed is to "disable rosetta"
N/A
References https://github.com/containers/podman-desktop-extension-bootc/issues/808
Follow documentation instructions on how to cross-arch build again.
> docs: add known issue cross-arch building

- packages/backend/assets/examples.json
- packages/backend/src/api-impl.spec.ts
- packages/backend/src/api-impl.ts
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/examples.ts
feat: backend for examples catalog
Adds the basic backend functionality for the examples catalog.
This adds a JSON file that lists all the currently available examples.
NOT INCLUDED IN PR. But part of this UI implementation:
https://github.com/user-attachments/assets/9205c5f3-40a6-4def-a4ee-2653c4165c25
Part of https://github.com/containers/podman-desktop-extension-bootc/issues/895
N/A
> feat: backend for examples catalog

- README.md
docs: remove $ from readme for easier copy and paste
Using the copy and paste button on GitHub results in including $.
We should remove the `$` from the README (on our podman desktop site, we
instead just ignore the $ at the beginning when copying and pasting).
N/A
N/A
N/A
> docs: remove $ from readme for easier copy and paste

- packages/backend/src/api-impl.ts
- packages/backend/src/vm-manager.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte
refactor: update vm manager + code suggestions
* Updates the VM manager so that it is more modular
* Fixes suggested code changes
* Updates DiskImageDetailsVirtualMachine check for websocket with a
timeout.
N/A
Closes https://github.com/containers/podman-desktop-extension-bootc/issues/953
Everything should work like normal launching a VM for arm or amd64
> refactor: update vm manager + code suggestions

- RELEASE.md
Adds docs for doing a release, matching what other extensions do and following the steps used for the 1.5.0 release.
N/A
Fixes #930.
Scan the steps or compare to AI Lab or Podman Desktop release process.
> chore: add release process

- packages/backend/assets/examples.json
chore: rename section
Renames the section instead of saying BootC, use the proper named
Bootable Container.
N/A
N/A
N/A
> chore: rename section

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/ExampleCard.spec.ts
- packages/frontend/src/lib/ExampleCard.svelte
- packages/frontend/src/lib/ExampleDetails.spec.ts
- packages/frontend/src/lib/ExampleDetails.svelte
- packages/frontend/src/lib/ExampleDetailsLayout.spec.ts
- packages/frontend/src/lib/ExampleDetailsLayout.svelte
- packages/frontend/src/lib/ExamplesCard.svelte
- packages/frontend/src/lib/markdown/MarkdownRenderer.svelte
feat: add example details page
* Adds clickable example details pages
* Tests for said pages
* Clickable link to source repo
https://github.com/user-attachments/assets/36588993-ad65-43ae-9e21-7666020bd9e6
Closes https://github.com/podman-desktop/extension-bootc/issues/974
Follow up issue is https://github.com/podman-desktop/extension-bootc/issues/1016
Click "More Details" on one of the examples
> feat: add example details page

- tests/playwright/src/bootc-extension.spec.ts
Fixes e2e tests that were failing due to broken navigation to webview.
https://github.com/podman-desktop/extension-bootc/issues/1053
> chore(test): fix navigation to webview

- packages/backend/src/constants.ts
chore: update bootc-image-builder image
Requires as I most recently encountered this issue during my testing:
https://github.com/osbuild/bootc-image-builder/issues/650
Updates the bib image
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1077
> chore: update bootc-image-builder image

- packages/backend/src/vm-manager.ts
chore: remove hvf acceleration from amd64 vm command
Should not have been added / was added when refactoring. `hvf` should
not be there for amd64 as it's cross-arch and not compatible (hvf only
working for arm).
N/A
Fixes https://github.com/podman-desktop/extension-bootc/issues/1088
1. Create an amd64 image
2. Run VM tab
3. Works / runs.
> chore: remove hvf acceleration from amd64 vm command

- .github/workflows/e2e-main.yaml
This pr is moving pnpm install step before node setup step.
> fix: e2e main test node setup is failing because of missing pnpm

- .github/workflows/e2e-main.yaml
Fixes e2e-main workflow failure at node setup step, by setting working-folder to correct location with pnpm-lock.yaml
> fix: e2e main workflow node setup step

- packages/frontend/src/lib/ExampleCard.spec.ts
- packages/frontend/src/lib/ExampleCard.svelte
chore: add telemetry for examples
Adds telemetry for building as well as pulling examples
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1047
Functions on example should work as normal.
> chore: add telemetry for examples

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/models/bootc.ts
feat: add build config configurator
* Adds automated way to create a build config json file
* Added to build page
https://github.com/user-attachments/assets/bbf18809-620f-46f5-ad5e-a02c8df69fd0
Closes https://github.com/podman-desktop/extension-bootc/issues/827
Use build config and configure / create your own custom build config
with users, filesystem, etc.
> feat: add build config configurator

- docs/vm_launcher.md
- packages/backend/src/api-impl.ts
- packages/backend/src/vm-manager.spec.ts
- packages/backend/src/vm-manager.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/lib/dashboard/Dashboard.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageColumnActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetails.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.spec.ts
- packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts
- packages/shared/src/BootcAPI.ts
feat: add linux VM experimental support
* Adds ability to test out VM for Linux users
* Arm and AMD64 support.
* Requires QEMU installed (there are prereqs as well as documentation
that outlines it)
Closes https://github.com/podman-desktop/extension-bootc/issues/878
1. Be on Linux
2. Install QEMU (see documentation)
3. Build an image
4. Click on the Virtual Machine tab after building (or the Launch VM
button).
> feat: add linux VM experimental support

- package.json
- packages/backend/package.json
- packages/frontend/package.json
- pnpm-lock.yaml
- tests/playwright/package.json
chore: revert back to vite 5 + update vitest
There are numerous issues updating to vite 6 is causing us:
* Issues with proper vitest and a failing test
* Blank pages for the extension
* Being forced to use a beta version of vitest to have it build
correctly.
https://github.com/user-attachments/assets/f650df65-a166-457a-bdb6-5abe658f73ac
Closes https://github.com/podman-desktop/extension-bootc/issues/1107
Be able to use the extension (using pnpm watch and passing in extension
folder) and not having a blank page.
> chore: revert back to vite 5 + update vitest

- README.md
- docs/vm_guide.md
- packages/backend/src/build-disk-image.ts
- packages/backend/src/constants.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/models/bootc.ts
- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-page.ts
Updates the image builder to a recent image, which includes support for the Google Cloud Engine (gce) image type.
Adds standard support for this image type to all the standard places in API/backend/frontend/tests. Using a single PR given how minimal and obvious the changes are in each part.
Fixes #1175.
Tests added. Select GCE and build successfully!
> feat: add support for Google Cloud Engine image type

- packages/frontend/src/lib/Card.svelte
- packages/frontend/src/lib/ExamplesCard.svelte
Just updates the child rendering to svelte 5 to remove the build warning. Since this is the only slot I just removed the name for simplicity.
N/A
Fixes #1206.
PR tests pass, no UI regressions on examples page.
> chore: update Card to svelte 5

- packages/backend/assets/examples.json
- packages/backend/src/api-impl.ts
- packages/backend/src/container-utils.ts
- packages/backend/src/machine-utils.ts
- packages/frontend/src/Examples.spec.ts
- packages/frontend/src/lib/ExampleCard.spec.ts
- packages/frontend/src/lib/ExampleCard.svelte
- packages/shared/src/BootcAPI.ts
feat: Adds option to pull arm64/amd64 examples
* Adds the ability to choose what initial arm64 or amd64 image example
you want
* Defaults to native architecture when initially loading
* Pulls the architecture correctly
https://github.com/user-attachments/assets/87effef0-74f4-4e4e-8131-0a5cf92a7928
Closes https://github.com/podman-desktop/extension-bootc/issues/1154
1. Go to examples page
2. Select from the drop down the arch you want
3. Pull the image & build
> feat: Adds option to pull arm64/amd64 examples

- packages/frontend/tailwind.config.cjs
chore: add vars for prose markdown generation
* Adds "prose" variable definitions in tailwind configuration for
markdown rendering. Without this, the rendered markdown does not work
in dark mode.
* See:
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1340
regarding a similar issue
https://github.com/user-attachments/assets/76c89136-3966-42b8-855b-400b6fdb84ec
Closes https://github.com/podman-desktop/extension-bootc/issues/1122
No test files needed.
View example details in both dark and light mode.
> chore: add vars for prose markdown generation

- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-page.ts
Removes required locators for not available type
https://github.com/podman-desktop/extension-bootc/issues/1240
> chore(test): fix broken e2e tests

- packages/backend/src/machine-utils.spec.ts
- packages/backend/src/machine-utils.ts
Just updates windows and linux to use PD env API instead of os.platform(), so that it is consistent with mac. Tests mock to mac for now, as they're not doing anything dependent on execution OS.
N/A
Fixes #1207.
PR checks.
> chore: use env for windows and linux

- packages/frontend/src/Navigation.spec.ts
Tests are checking that when you're at each route, the corresponding nav item (and only that) is selected in the navigation. SettingsNavItem added an extra div in the hierarchy so test s checking the wrong div.
Ideally SettingsNavItem would have aria labels, and the test would look at more of the hierarchy - but it was only a minute to find the problem, fix the test, and add the missing test for examples. If it happens again we can do something better but for now just update the test (and add the missing paths).
N/A
Fixes #1235.
PR test passes.
> fix: update setting nav test to match 1.16

- eslint.config.mjs
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/src/Examples.svelte
- packages/frontend/src/lib/BootcStatusIcon.svelte
- packages/frontend/src/lib/dashboard/Dashboard.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte
Enable no-explicit-any linting rule and fix issues.
N/A
Part of #1245.
Code review, pr checks.
> chore: no-explicit-any

- packages/backend/src/extension.ts
- packages/shared/src/messages/MessageProxy.ts
The RPC message proxy should be disposed on shutdown. This change just disposes it properly, and drops the timeout down to 5s (aligns with AI Lab change, may also help with a timeout during shutdown).
N/A
Possibly the cause of https://github.com/podman-desktop/podman-desktop/issues/10926.
Fixes #1263.
Try to reproduce https://github.com/podman-desktop/podman-desktop/issues/10926.
> chore: update rpc message proxy and dispose correctly

- packages/backend/src/extension.ts
Signed-off-by: Philippe Martin <phmartin@redhat.com>
Create storage path before to watch a file inside it, to avoid the app crash 
N/A
Fixes https://github.com/podman-desktop/podman-desktop/issues/10926
> fix: create storage path

- packages/backend/package.json
chore: fix bootc label colouring on dark / light mode
Fixes the colour showing in dark / light mode on the image page. As
before it was not picking up the tailwind-specific colour.
https://github.com/user-attachments/assets/9a8e3953-5eda-4377-ad98-4cd51d8d69d4
Closes https://github.com/podman-desktop/extension-bootc/issues/1174
1.Pull a bootc test image
2. See that the label shows now
> chore: fix bootc label colouring on dark / light mode

- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageColumnActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageConnectionStatus.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsSummary.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte
- packages/frontend/src/lib/disk-image/DiskImagesList.svelte
- packages/frontend/src/lib/disk-image/columns/Actions.spec.ts
- packages/frontend/src/lib/disk-image/columns/Actions.svelte
- packages/frontend/src/lib/disk-image/columns/Folder.spec.ts
- packages/frontend/src/lib/disk-image/columns/Folder.svelte
- packages/frontend/src/lib/disk-image/columns/Image.spec.ts
- packages/frontend/src/lib/disk-image/columns/Image.svelte
- packages/frontend/src/lib/disk-image/columns/props.ts
Moves disk image columns and details pages to Svelte 5.
Column files are reorganized into /columns folder as discussed in https://github.com/podman-desktop/podman-desktop/issues/11035.
N/A
Part of #1295.
PR checks, basic build list validation.
> chore: svelte 5 disk image columns and details

- packages/backend/src/extension.ts
With the multi-channel RPC in #1300 we switched from automatic init via constructor to requiring init() to be called explicitly, I just missed committing this one critical line.
N/A
Fixes #1301.
See issue, just check examples or builds page appears.
> chore: missing rpc init

- packages/frontend/src/lib/BootcStatusIcon.spec.ts
- packages/frontend/src/lib/BootcStatusIcon.svelte
- packages/frontend/src/lib/DiskImageIcon.svelte
The icons should not be using hard-coded color values. Bootc status icon switched to using the appropriate color variables. The red is a little bright and we lose the sky blue for building :( but these are the correct colors and now match Podman Desktop.
Disk image icon uses #fff since the mask should be pure FFF (should not have been using the palette in the first place).
Part of #975.
Check Disk Image page.
> chore: icon color cleanup

- packages/backend/src/api-impl.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte
- packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts
- packages/frontend/src/lib/disk-image/DiskImagesList.svelte
- packages/shared/src/BootcAPI.ts
Moving to svelte 5, state objects are proxied. Normally that's an implementation detail, but when you try to pass the proxies through rpc they can't be cloned and result in errors.
We could use $state.snapshot(build) every time we pass objects from the UI to the API, but we really shouldn't be passing whole objects to the backend and blindly trusting that the objects (including all properties) match what the backend knows anyway.
This changes the three affected API functions to accept ids instead of objects, and the backend looks up the objects before acting. Although it's slightly more work on the backend, this is a better/more robust API, and also avoids the svelte 5 proxy issue.
N/A
Fixes #1304.
PR checks, delete a build, start a VM. Tests added to check we're passing strings.
> chore: using simple objects in rpc api (to avoid snapshots)

- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
The disk image details page didn't have any actions, which is different from every other details page. This adds actions, but only Delete since the other actions are essentially just links to tabs here.
Fixes #1299.
Delete a disk image from within the details page.
> chore: add missing delete action

- packages/backend/vitest.config.js
Code coverage reports were including lots of files that aren't in the package.
As usual, my first step was to steal from the AI Lab extension! :) The fix is in vitest.config, but I also found some minor differences/formatting in vite.config that I thought were worth picking up and aligning to.
Coverage report down from multiple pages to:
```
% Coverage report from v8
----------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                 
----------------------|---------|----------|---------|---------|---------------------------------------------------------------------- …
```
> chore: fix backend code coverage report

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/models/bootc.ts
feat: add anaconda iso module enable / disable
* Adds the ability to disable or enable any anaconda iso modules
* Added to build page with ability to choose enable/disable and
add/remove as many as you want.
https://github.com/user-attachments/assets/e20ae912-3c81-49ed-8095-9ff6f69aa477
Closes https://github.com/podman-desktop/extension-bootc/issues/1028
1. Add a few entries from within the build page.
2. Check your `config.json` after creation (it's in the same folder as
your output folder).
3. Confirm modules have been put in there.
> feat: add anaconda iso module enable / disable

- biome.jsonc
- package.json
- packages/backend/package.json
- packages/backend/tsconfig.json
- packages/backend/vite.config.js
- packages/frontend/src/app.css
- packages/frontend/tailwind.config.cjs
- packages/frontend/vite.config.js
- packages/shared/tsconfig.json
- packages/shared/vite.config.js
- packages/shared/vitest.config.js
- pnpm-lock.yaml
- tests/playwright/src/bootc-extension.spec.ts
From a comment in #1338 - we're missing formatting of config files.
If we're going to fix formatting, I figured we may as well copy from Podman Desktop and upgrade to / align with biome. First commit copies in the biome config and package.json changes, second commit is the first pass running it.
N/A
N/A
PR check.
> Switch to biome for formatting

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
The build page still had a link using hard-coded color values, just convert to a Link like all the others.
N/A
Part of #975.
When you have no bootc images the link should still appear and work.
> chore: remove a href from build page

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/vm_launcher.md
- package.json
This repo didn't have formatting enabled for markdown, this just enables it the same as the podman-desktop repo (prettier for md, biome for everything else).
N/A
N/A
Edit a markdown file and use `pnpm format:fix`.
> chore: use prettier for markdown

- eslint.config.mjs
- packages/frontend/package.json
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/vite.config.js
- packages/frontend/vite.tests.setup.js
- pnpm-lock.yaml
Uses the same fix as https://github.com/podman-desktop/podman-desktop/pull/9287 to mock HTML canvas. Also has some minor fixes to mocking and error output in second commit.
Output from `pnpm test:frontend` drops from 285 to 116 lines, making it much easier to debug new tests.
N/A
Fixes #1353.
`pnpm test:frontend`
> chore: mock html canvas and fix mocking to reduce output

- packages/backend/src/build-disk-image.spec.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts
- packages/frontend/src/stores/rpcReadable.spec.ts
From a comment on #1339, we use a spy in several places where we should now be using vi.mocked(). This just cleans up the low hanging fruit.
N/A
Part of #975.
Code review, PR checks still green.
> chore: replace spy with vi.mocked

- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.svelte
#1286 caused a regression where fetchFolderLogs is no longer called every 2s. Added () and a catch so that it's called correctly. Also, refreshInterval is a constant so shouldn't be part of the state.
Tempted to make the interval a parameter to reduce test time, but started by just adding a test that waits to confirm the timeout starts triggering with 3.5s.
N/A
Fixes #1303.
Start a build, open logs, and confirm that the output keeps updating.
> fix: refresh log timeout not triggering

- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/shared/src/BootcAPI.ts
- packages/shared/src/models/bootc.ts
feat: add kickstart file to interactive installer
Adds the ability to provide a kickstart file to the interactive
installer.
Closes https://github.com/podman-desktop/extension-bootc/issues/1027
1. Save an example kickstart file:
```sh
#platform=x86, AMD64, or Intel EM64T
auth --enableshadow --passalgo=sha512
cdrom
graphical
firstboot --enable
keyboard --vckeymap=us --xlayouts='us'
lang en_US
```
2. Use interactive installer on the build page and select the file.
3. Confirm you are able to build it / it passes validation with iso.
> feat: add kickstart file to interactive installer

- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/build-disk-image.ts
Either during increasing our linting rules and properly handling promises, or updating the message proxy, the behaviour of returning a promise from buildDiskImage() changed. Instead of returning the window.withProgress promise immediately, it now waits until the task/promise is complete before returning. As a result, the build always 'times out' and you receive an error in the UI.
The correct behaviour should be returning immediately after starting the background task. This just adds a catch block so that we can remove the return and not await.
I'll be honest, I have no idea how to correctly test for this behaviour. :)
N/A
Fixes #1302.
See #1302. Start a build and confirm you're redirected to the build logs instead of receiving a timeout error.
> fix: correctly kick off build in background

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
Uses the new Expandable component for the three toggles on the build page, just some minor reuse/consistency.
Before:
https://github.com/user-attachments/assets/5f6b5895-2d83-4a95-9c02-f158c9c48140
After:
https://github.com/user-attachments/assets/97b813b5-9fc0-48ed-85ce-2306b35c2b5f
Part of #975.
Check Build page for minor UI. improvement and no regressions.
> chore: use expandable component in build page

- packages/frontend/src/lib/BootcStatus.svelte
- packages/frontend/src/lib/disk-image/DiskImagesList.svelte
- packages/frontend/src/lib/disk-image/columns/Status.svelte
While working on #862 I noticed that the disk image status column isn't in the folder with the other columns, and doesn't follow the same naming or props patterns. This just moves the file into the correct location/ naming/props/svelte 5 as the other disk image columns.
N/A
Found while working on #862.
PR checks, compare to other files in /columns.
> chore: fix pattern for disk image status column

- packages/backend/src/api-impl.ts
- packages/frontend/src/lib/dashboard/Dashboard.spec.ts
- packages/frontend/src/lib/dashboard/Dashboard.svelte
- packages/frontend/src/lib/examples/Examples.spec.ts
- packages/frontend/src/lib/examples/ExamplesCard.svelte
- packages/frontend/src/stores/imageInfo.ts
- packages/shared/src/messages/Messages.ts
For disk images (historyInfo) we use a store that's updated via an event (MSG_HISTORY_UPDATE). For container images things are a lot more complicated:
- The list of images on the Dashboard and Examples pages was not reactive, just comes from the API on page load.
- pullImage() is async - but the promise would never fail.
- Since bootc images tend to be > 1Gb, pullImage() almost always times out in the RPC browser.
- A MSG_IMAGE_PULL_UPDATE event was fired and the pages would update state accordingly based on the event.
- The dashboard has a disclaimer after 5s - but this would show in 10s or not at all b/c pullImage would time out.
This commit fixes pullImage and replaces the event logic with an image store:
- pullImage() now returns errors if they occur, and is added to the 'no timeout' …
> chore: refactor image pull logic and provide image store

- tests/playwright/src/bootc-extension.spec.ts
- tests/playwright/src/model/bootc-examples-page.ts
- tests/playwright/src/model/bootc-page.ts
Adds new e2e tests to check building of example bootable images.
https://github.com/podman-desktop/extension-bootc/issues/1376
> chore(test): creating e2e tests for examples bootc page

- packages/frontend/src/lib/dashboard/Dashboard.spec.ts
- packages/frontend/src/lib/dashboard/Dashboard.svelte
chore: switch to officially hosted examples
The examples on the fedora bootc gitlab
(https://gitlab.com/fedora/bootc/examples) are now hosted for both arm64
and amd64.
We can now replace our own "self maintained" examples with the official
examples which are better maintained.
This has been tested and you can see there are both image architectures
available:
```sh
▶ podman pull registry.gitlab.com/fedora/bootc/examples/httpd:latest --platform linux/arm64
Trying to pull registry.gitlab.com/fedora/bootc/examples/httpd:latest...
Getting image source signatures
Copying blob sha256:c592249cccb1f5c0a13ab4f62723b5ad4cdc85e68382963d757f0e9a62d4be84
Copying blob sha256:7c50fb37076aedf81eccd41a3ca88071f1aa74b1b235db858836661b7ac6369d
Copying blob …
```
> chore: switch to officially hosted examples

- package.json
Explicitly state the dependencies with build scripts to execute during ie. install lifecycle phase in pnpm v10. This will enable to e2e tests to run.
We have alternatives, I went with the minimal working solution, other options:
```
"onlyBuiltDependencies": ["electron", "@biomejs/biome", "esbuild", "svelte-preprocess"] -> building those that appeared on the warning
OR
"neverBuiltDependencies": [] -> to build any
```
When I run `pnpm approve-builds` locally, it updated pnpm-workspace.yaml file instead of package.json.
https://github.com/podman-desktop/extension-bootc/issues/1447
E2E tests should be passing now.
> chore: allow dependencies to be built with pnpm v10

- packages/backend/src/constants.ts
chore: update rhel bootc-image-builder image
* Update the rhel bootc-image-builder image to 9.5 over 9.4
* Confirmed working with fedora / centos / rhel 10 building.
N/A
Part of https://github.com/podman-desktop/extension-bootc/issues/1363
1. Change the default setting for image builder to the RHEL one
2. Build any image (fedora, centos, etc.)
3. Builds with no errors.
> chore: update rhel bootc-image-builder image

- README.md
chore: add rhel 10 beta, add fedora 42
* Adds RHEL 10 beta (confirmed able to build with upstream
bootc-image-builder).
* Change our Fedora image to Fedora 42 now that's stable / latest
release.
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1363
1. Try to build RHEL 10 Beta using
`registry.redhat.io/rhel10-beta/rhel-bootc:latest`
2. Confirm it builds correctly / passes
> chore: add rhel 10 beta, add fedora 42

- packages/frontend/src/lib/FirstImage.spec.ts
- packages/frontend/src/lib/FirstImage.svelte
- packages/frontend/src/lib/dashboard/Dashboard.svelte
I want to use the same 'load first image' controls on the bootable image empty screen as what we have on the Dashboard today. This just extracts the UI elements out of the Dashboard and into its own reusable component, which is better code separation anyway.
N/A
Part of #862.
Just code review.
> chore: extract first image component

- packages/frontend/src/lib/examples/ExamplesCard.svelte
The More Details button doesn't fit within the example cards where the cards are too narrow. Instead of changing the design, simple fix is just to bump the responsive breakpoints so that the cards never get quite as narrow.
Before:
After:
https://github.com/user-attachments/assets/914ebd0d-bd8c-4d82-8465-2d3b10e552dd
Fixes #1505.
Go to Examples page and try it at different widths.
> fix: update responsive breakpoints to avoid example overflow

- tests/playwright/src/bootc-extension.spec.ts
Revers a previous change that broke e2e test navigation validation
> chore(test): revert heading validation change

- packages/frontend/src/lib/BootcStatusIcon.spec.ts
- packages/frontend/src/lib/BootcStatusIcon.svelte
As we add images to the UI we'll need the status icon to support two new states: used and unused. Unused doesn't require any changes (it's the default styling) but used needs to be treated the same way as 'success' for disk images.
N/A
Part of #862.
PR checks, code review.
> chore: bootable image status icon

- packages/frontend/src/lib/images/ImageInfoUI.ts
- packages/frontend/src/lib/images/image-utils.spec.ts
- packages/frontend/src/lib/images/image-utils.ts
As we add a bootable images page we need to convert images to a simpler UI object for easier display and manipulation as we've done in Podman Desktop. This is heavily copied from that code, with a bunch of simplification and cleanup for the bootc case.
Note: support for manifests is not included as it looks like the API is not exported from Podman Desktop, will be followup issue.
N/A
Part of #862.
Just PR checks, code review.
> chore: bootable images UI object

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
chore: small check, do prereqs before building
On the build page, we should do a prereqs check to see if the podman
machine is even running.
This adds a prereq check at the beginning to make sure that it errors
out before the user fills out the form.
I have also made sure that validation is now captures inside of a try /
catch, which it wasn't before.
No need to checks elsewhere, as we have error outputs when trying to pull:
Closes https://github.com/podman-desktop/extension-bootc/issues/701
1. Purposely stop podman machine
2. Go to build
3. See it errors out when trying to press button.
> chore: small check, do prereqs before building

- packages/frontend/src/App.svelte
- packages/frontend/src/Navigation.svelte
- packages/frontend/src/lib/dashboard/Dashboard.svelte
- packages/frontend/src/lib/images/ImageActions.spec.ts
- packages/frontend/src/lib/images/ImageActions.svelte
- packages/frontend/src/lib/images/ImageEmptyScreen.spec.ts
- packages/frontend/src/lib/images/ImageEmptyScreen.svelte
- packages/frontend/src/lib/images/ImagesList.spec.ts
- packages/frontend/src/lib/images/ImagesList.svelte
- packages/frontend/src/lib/images/columns/Actions.svelte
- packages/frontend/src/lib/images/columns/Name.spec.ts
- packages/frontend/src/lib/images/columns/Name.svelte
- packages/frontend/src/lib/images/columns/Status.spec.ts
- packages/frontend/src/lib/images/columns/Status.svelte
- packages/frontend/src/lib/images/columns/props.ts
Adds a basic bootable images page into the navigation, and linked from the Dashboard. Images just have Name, Age, Size, and a build action for now.
Things not included here, for future PRs:
- Navigation to image details (opening bug in Podman Desktop).
- Support for manifests (unclear that Podman Desktop exports enough API).
- Ability to delete images (just needs a little work).
- Images are not marked as 'used' (requires a container store).
Main part of #862.
Open the Images page from the navigation and try different things, e.g. deleting all local bootc images, filtering, going to Build page.
> feat: bootable images page

- packages/backend/src/api-impl.spec.ts
- packages/backend/src/api-impl.ts
- packages/frontend/src/lib/images/ImagesList.spec.ts
- packages/frontend/src/lib/images/ImagesList.svelte
- packages/shared/src/BootcAPI.ts
Adds API for getting the list of containers and uses it in the images list. Since the requirements are simple (you can't change containers in any way within the page) it's just caching the list on mount.
Part of #862.
Pull at least 2 images, and create a container in Podman Desktop based on one of them. The status icon and checkbox enablement should match the Images page in Podman Desktop.
API test added, status icon and other parts had tests in previous PR.
> chore: show used images via container list

- packages/shared/src/messages/NoTimeoutChannels.ts
Calls to the backend that involve user interaction (e.g. picking a folder) could be indefinite and should be excluded from timeouts.
N/A
Fixes #1542.
Open the Build page and click the browse button. Wait more than 5s to pick one and confirm it still works.
> fix: no timeout for user interaction

- packages/frontend/src/Build.svelte
I noticed this when implementing a new page, our Build svelte page has some of the inputs in a separate div that doesn't do anything.  I incorrectly placed a bunch of these elements in the div.  Removing the div should not have any effect on the UI/UX.
No changes above.
N/A, chore.
See build page is fine before and after.
> chore: update build page unused div

- packages/frontend/src/Build.svelte
chore: fix spacing in build page.
Adds `mb-3` to the sections to add more spacing between sections.
Removing the class from the PR:
https://github.com/podman-desktop/extension-bootc/pull/1573 caused the
spacing to revert back to being close-together.
Before:
After:
N/A, no issue.
Just view the build page :)
> chore: fix spacing in build page.

- package.json
- packages/backend/__mocks__/@podman-desktop/api.js
- packages/backend/src/api-impl.spec.ts
- packages/backend/src/api-impl.ts
- packages/backend/src/build-disk-image.spec.ts
- packages/backend/src/extension.spec.ts
- packages/backend/src/macadam.spec.ts
- packages/backend/src/macadam.ts
- packages/shared/src/BootcAPI.ts
- packages/shared/src/messages/NoTimeoutChannels.ts
- pnpm-lock.yaml
feat: add backend support for Macadam create image
* Adds Macadam create image backend support
* Adds unit tests and constants updates
N/A
Reference: https://github.com/podman-desktop/extension-bootc/issues/1521
1. Run backend unit tests
2. Test API integration with frontend.
> feat: add backend support for Macadam create image

- packages/frontend/package.json
- packages/frontend/src/App.svelte
- packages/frontend/src/CreateVM.svelte
- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetails.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
- packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts
- packages/frontend/src/lib/disk-image/columns/Actions.spec.ts
- packages/shared/src/messages/NoTimeoutChannels.ts
- pnpm-lock.yaml
feat: add Macadam create image UI
* Removes the experimental VM tab for macOS
* Replaces the VM button with Macadam support
* Adds new Macadam create image screen
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1521
Closes https://github.com/podman-desktop/extension-bootc/issues/1520
Closes https://github.com/podman-desktop/extension-bootc/issues/876
1. Create a GitHub token (legacy permission token) with read:packages permission
2. Create '.npmrc' in the root folder with the token
3. Run 'pnpm install'
4. Run 'pnpm watch'
5. Launch in Podman Desktop ('pnpm watch --extension-folder ../bootc/packages/backend/media')
6. Build an image in the bootc extension
7. Press the VM button and confirm creation succeeds.
> feat: add Macadam create image UI

- packages/frontend/src/CreateVM.spec.ts
chore: add tests for CreateVM.svelte
Adds some missing tests for CreateVM.svelte by covering 89% of the file.
N/A
N/A
Tests run themselves :)
> chore: add tests for CreateVM.svelte

- packages/frontend/src/App.svelte
- packages/frontend/src/CreateVM.svelte
- packages/frontend/src/lib/disk-image/DiskImagesList.svelte
Adds a Create VM button to the disk image list, matching what we have for building disk images (you can launch on an image to pre-fill the page, or you can just open the build page and select everything).
Since this is the first time the Create VM form is used without input params, the route has to be added and parameters made optional.
Part of #1588
Open Disk Images page and confirm that the Create VM button is there and opens the form.
> chore: add create vm button to disk image list

- packages/backend/assets/examples.json
chore: add more examples to the examples page
* Adds cloud init example, wifi and kernel module management examples.
* There are missing README's vs upstream for wifi and kernel module, so they have
been added here instead.
https://github.com/user-attachments/assets/2ab15249-4b8e-422d-88e0-927490a0af13
Closes https://github.com/podman-desktop/extension-bootc/issues/1510
View examples page and see the new examples.
> chore: add more examples to the examples page

- packages/backend/src/api-impl.ts
- packages/frontend/src/CreateVM.svelte
- packages/frontend/src/lib/Link.svelte
- packages/shared/src/BootcAPI.ts
Turns the text Settings > Resources into a link to the correct page. Requires support for triggering an action from the Link component, and routing to the backend in order to trigger the Podman Desktop navigation API.
Part of #1588.
Create a VM and just check that Settings > Resources is now a working link.
> chore: add link to resources

- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
Just switches to fake timers so that we can advance exactly one step instead of being dependent on timing between the component and waitFor() test.
N/A
Fixes #1624.
Confirm PR checks pass.
> fix: use fake timers to avoid timing issue in disk image test

- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
The previous change switched to a fixed timer which is much more predictable and worked on main, but still fails on most builds. The failure is at least repeatable now, and shows the next problem: onMount is async, so there's no guarantee that the initial fetch or call to setInterval() has happened when we advance the timer and do the test.
This spys on setInterval to confirm that onMount() has executed and the initial fetch was done, then advances the timer once to make sure we've done exactly one step. Being called twice appears to be vitest artifact; does not happen when testing.
N/A
Fixes #1624.
PR checks pass.
> fix: wait for onmount and use fixed timer advance

- packages/frontend/src/lib/disk-image/DiskImageDetailsBuild.spec.ts
Running the test `Refreshes logs correctly` alone works on my machine, running the test file make the test fails, I believe this may be some kind of test isolation problem.
1. Set window mock in the beforeAll
2. Mock return value in the beforeEach
3. Replace `vi.clearAllMock` with `vi.resetAllMock`
4. Init & Reset the fake timers before and after each test
- Pipeline should be 🟢
> fix(DiskImageDetailsBuild.spec): test isolation through fake timers

- .dockerignore
- Containerfile
chore: manually add macadam.js to the Containerfile
* Modifies the Containerfile so that the macadam.js library and binaries so that they can be used via OCI image install.
N/A, no UI changes.
Closes https://github.com/podman-desktop/extension-bootc/issues/1598
1. Build the image (podman build) and push it to a container registry
2. Install via the container registry
3. See everything else works fine
> chore: manually add macadam.js to the Containerfile

- packages/backend/package.json
- packages/backend/src/extension.spec.ts
- packages/backend/src/extension.ts
- packages/backend/src/macadam/base-check.ts
- packages/backend/src/macadam/logger.ts
- packages/backend/src/macadam/macadam-machine-stream.ts
- packages/backend/src/macadam/utils.ts
- packages/backend/src/macadam/win/hyperv-helper.ts
- packages/backend/src/macadam/win/powershell.ts
- packages/backend/src/macadam/win/utils.ts
- packages/backend/src/macadam/win/wsl-helper.ts
- packages/backend/vite.config.js
- pnpm-lock.yaml
Adds a Bootc VM provider to Settings > Resources. Only bootc extension created VMs appear in this section.
The bulk of code is direct copy pasta from the Macadam extension, which we'll need to keep in sync until we figure out how to share / where VMs belong. I've only added two 'eslint-disable sonarjs/no-ignored-exceptions' (better to keep code in sync than fix these in one place) and changed the labels/ descriptions.
Two new dependencies added: ssh2 and compare-versions.
Main part of #1597.
Create a couple VMs, confirm they work identically to before (but without requiring another extension).
> feat: bootc vm provider

- packages/frontend/src/CreateVM.svelte
With #1599 and #1600 merged, the bootc extension is standalone and does not require the (now renamed) Macadam extension. This just removes the two references in the UI to corrects the text to make it consistent.
Just removing text.
Last part of #1597.
Fixes #1570.
Check text on screen when creating a VM and on successful completion.
> chore: clean up references to macadam extension

- .dockerignore
- Containerfile
chore: add ssh2 to Containerfile
Temporary fix in order to get the next release out. We should work
post-release on vite / plugin script for this.
Adds ssh2 (and it's other dependencies) to node_modules.
N/A
Part of https://github.com/podman-desktop/extension-bootc/issues/1633
1. `pnpm build`
2. Build the container image
3. Install VIA CONTAINER IMAGE within podman desktop
4. Test that terminal functionality works fine under Resources >
Settings.
> chore: add ssh2 to Containerfile

- README.md
- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
feat: enables virtual machine creation for linux
* Modifies the if statement so that it shows for both mac and linux and
not Windows
* Updates the macadam.js package to the most up-to-date / latest one.
Closes https://github.com/podman-desktop/extension-bootc/issues/1587
Must test this out in the OCI image mode / don't use `pnpm watch`,
although `pnpm watch` will work, it's better to test this out in a
"production" environment.
1. Follow the README to install the required binaries
2. `pnpm build`
3. BUILD the image with `podman build`
4. Push the image somewhere
5. Install the OCI image under extensions.
6. Test out creating / starting / access the terminal on the VM.
> feat: enables virtual machine creation for linux

- packages/frontend/src/lib/disk-image/DiskImageDetails.svelte
chore: remove virtual machine experimental tab
Removes the tab since we no longer use it, we use macadam instead now.
N/A
N/A
1. Install extension
2. No longer see VM tab for Linux
> chore: remove virtual machine experimental tab

- packages/backend/package.json
- packages/backend/src/extension.ts
- pnpm-lock.yaml
Switching to correct macadam version with binaries, and adding try/catch around the init to avoid extension failure and have better logging if init fails.
N/A
Fixes #1637.
Install on fresh machine and confirm macadam gets installed correctly / extension starts correctly.
> chore: switch macadam versions, catch init failure

- Containerfile
- packages/backend/package.json
The catalog will enforce this separately, but we now depend on VM support in Podman Desktop, which was added in the 1.18 release.
N/A
N/A
Try to install on current and older version, Podman Desktop should block from older version only.
> chore: update minimum pd version

- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
Only raw and qcow2 images are supported for now. This adds the correct path for qcow2 and doesn't assume the raw path for other types - user will see the error when they go to the page.
Had to update the invalid logs button test first, then added two tests for clicking on the create VM button for raw and qcow2. Just checking the final (btoa encoded) output for now.
N/A
Fixes #1650.
Click on the button to create a VM from both a raw and qcow2 disk image and confirm the paths are correct.
> fix: prefill correct path for qcow2 images

- packages/frontend/src/lib/disk-image/DiskImageActions.spec.ts
- packages/frontend/src/lib/disk-image/DiskImageActions.svelte
Only raw and qcow2 images are supported for now. This adds the correct path for qcow2 and doesn't assume the raw path for other types - user will see the error when they go to the page.
Had to update the invalid logs button test first, then added two tests for clicking on the create VM button for raw and qcow2. Just checking the final (btoa encoded) output for now.
N/A
Fixes #1650.
Click on the button to create a VM from both a raw and qcow2 disk image and confirm the paths are correct.
> 1.9.x: fix: prefill correct path for qcow2 images

- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
chore: add disclaimer that to test, have to add ssh key
* Adds a small disclaimer that only appears on mac or linux that you
should add your SSH key + do output as raw or qcow2
* For this PR, I also did an alternative way of doing tests since I did
not want to copy / paste and only be changing one thing. So in this PR
the tests are "table-based".
Closes https://github.com/podman-desktop/extension-bootc/issues/1569
1. pnpm watch
2. See that the disclaimer is shwon on the build page.
> chore: add disclaimer that to test VM, have to add ssh key

- tests/playwright/src/bootc-extension.spec.ts
Adds bootc e2e test for building disk image with rhel builder
https://github.com/podman-desktop/extension-bootc/issues/1377
> chore(test): add rhel builder e2e test

- packages/frontend/src/lib/disk-image/DiskImagesList.spec.ts
- packages/frontend/src/lib/disk-image/DiskImagesList.svelte
chore: rename Disk Images to disk images for search
Changes the capitalization to fit conventional other sections of Podman
Desktop
Closes https://github.com/podman-desktop/extension-bootc/issues/1528
See change in UI that it is now "Search disk images"
> chore: rename Disk Images to disk images for search

- packages/backend/src/constants.ts
chore: update bib to remove missing platform id issue
Updates BIB to remove an issue with missing PLATFORM_ID with Fedora
43.
Closes https://github.com/podman-desktop/extension-bootc/issues/1806
Use this bootc extension with bib and see everything builds correctly,
etc.
> chore: update bib to remove missing platform id issue

- README.md
chore(docs): Add more information regarding cross-arch building on macOS
* Removes out outdated documentation
* Adds documentation on how to build cross-arch when on macOS
* Add information regarding why it does not work at the moment.
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1736
N/A, docs related.
> chore(docs): Add more information regarding cross-arch building on macOS

- package.json
- packages/frontend/src/Build.spec.ts
- packages/frontend/src/Build.svelte
- packages/frontend/src/lib/dashboard/Dashboard.svelte
- packages/frontend/src/lib/disk-image/DiskImageDetailsVirtualMachine.svelte
- packages/shared/src/repository-infos.ts
- packages/shared/tsconfig.json
This PR introduces the repository field in package.json, and it uses it across the extension Typescript code. It also fixes the outdated repository name found.
Fixes #1836
This is a follow-up of https://github.com/podman-desktop/extension-bootc/pull/1830/files#r2224668335
> refactor: use repository from package.json

- packages/backend/package.json
- packages/frontend/package.json
- pnpm-lock.yaml
chore: update to macadam 0.2.0
The new release of macadam 0.2.0 introduces new features such as running
multiple VM's.
This updates our depedency to macadam 0.2.0
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1904
1. Build a disk image
2. Be able to create a virtual machine again (see the README for a
tutorial on how to create one: https://github.com/podman-desktop/extension-bootc?tab=readme-ov-file#usage
> chore: update to macadam 0.2.0

- .github/dependabot.yml
See PRs #1949 and #1950 - commitlint wasn't in the dependabot group with its name. This just moves it in so that the group is correctly batched next time.
N/A
N/A
Wait for next commitlint update...
> chore: add commitlint to its group

- packages/backend/package.json
- packages/frontend/package.json
- pnpm-lock.yaml
chore: upgrade to new version of macadam including opt fix
Updates to the newest version of macadam that now installs the binary to
`/usr/local/bin/macadam`
N/A
Closes https://github.com/podman-desktop/extension-bootc/issues/1903
N/A, everything should work as usual.
> chore: upgrade to new version of macadam including opt fix
